/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Область доступа текущего субъекта */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Продукты, видимые субъекту */
        get: operations["listProducts"];
        put?: never;
        /** Создать продукт (PG-01) */
        post: operations["createProduct"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products/{productId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                productId: components["parameters"]["productId"];
            };
            cookie?: never;
        };
        /** Продукт */
        get: operations["getProduct"];
        /** Изменить продукт */
        put: operations["updateProduct"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products/{productId}/strategic": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                productId: components["parameters"]["productId"];
            };
            cookie?: never;
        };
        /** Стратегический срез продукта (PG-10) */
        get: operations["getStrategicSlice"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products/{productId}/capabilities": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                productId: components["parameters"]["productId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Создать возможность (PG-02) */
        post: operations["createCapability"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products/{productId}/features": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                productId: components["parameters"]["productId"];
            };
            cookie?: never;
        };
        /** Фичи продукта (приватный контур) */
        get: operations["listFeatures"];
        put?: never;
        /** Создать фичу (PG-02) */
        post: operations["createFeature"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products/{productId}/feature-values": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                productId: components["parameters"]["productId"];
            };
            cookie?: never;
        };
        /** Rollup производного спроса по продукту (PG-07) */
        get: operations["listFeatureValues"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/features/{featureId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                featureId: components["parameters"]["featureId"];
            };
            cookie?: never;
        };
        /** Фича */
        get: operations["getFeature"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Изменить фичу (дата — через shift-date) */
        patch: operations["updateFeature"];
        trace?: never;
    };
    "/features/{featureId}/requirements": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                featureId: components["parameters"]["featureId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Добавить требование (PG-02) */
        post: operations["createRequirement"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/features/{featureId}/shift-date": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                featureId: components["parameters"]["featureId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Изменить плановую дату с причиной и распространить сдвиг (PG-08, RM-03) */
        post: operations["shiftFeatureDate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/features/{featureId}/value": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                featureId: components["parameters"]["featureId"];
            };
            cookie?: never;
        };
        /** Rollup одной фичи (PG-07) */
        get: operations["getFeatureValue"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/links": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Связи, видимые субъекту (PG-03, PG-09) */
        get: operations["listLinks"];
        put?: never;
        /** Создать связь; при цикле — 409 с путём (PG-05) */
        post: operations["createLink"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/links/{linkId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                linkId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Удалить связь */
        delete: operations["deleteLink"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/hubs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Роль хаба по входящей связности (PG-06) */
        get: operations["listHubs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/contracts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Интеграционные контракты (PG-04) */
        get: operations["listContracts"];
        put?: never;
        /** Создать контракт */
        post: operations["createContract"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/contracts/{contractId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                contractId: string;
            };
            cookie?: never;
        };
        /** Контракт со сроком готовности */
        get: operations["getContract"];
        /** Изменить контракт */
        put: operations["updateContract"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/settings/graph": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Коэффициенты критичности (PG-07) */
        get: operations["getGraphSettings"];
        /** Изменить коэффициенты */
        put: operations["updateGraphSettings"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/audit/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Проверка целостности журнала аудита (NF-S05) */
        post: operations["verifyAudit"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products/{productId}/signals": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                productId: components["parameters"]["productId"];
            };
            cookie?: never;
        };
        /** Сигналы продукта (приватный контур) */
        get: operations["listSignals"];
        put?: never;
        /** Принять сигнал вручную (SG-01) */
        post: operations["ingestSignal"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products/{productId}/signals/triage": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                productId: components["parameters"]["productId"];
            };
            cookie?: never;
        };
        /** Очередь разбора по сроку (SG-03) */
        get: operations["triageQueue"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/signals/import/crm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Импорт сигналов из порта CRM (SG-01) */
        post: operations["importSignalsFromCRM"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/signals/{signalId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                signalId: components["parameters"]["signalId"];
            };
            cookie?: never;
        };
        /** Сигнал */
        get: operations["getSignal"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/signals/{signalId}/triage": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                signalId: components["parameters"]["signalId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Изменить статус и срок разбора (SG-03) */
        post: operations["triageSignal"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/signals/{signalId}/link": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                signalId: components["parameters"]["signalId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Привязать к фиче или контракту с сохранением денежного веса (SG-05) */
        post: operations["linkSignal"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scoring-models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Модели оценки (PR-01) */
        get: operations["listScoringModels"];
        put?: never;
        /** Создать модель оценки */
        post: operations["createScoringModel"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scoring-models/{modelId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                modelId: components["parameters"]["modelId"];
            };
            cookie?: never;
        };
        get?: never;
        /** Изменить модель */
        put: operations["updateScoringModel"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scoring-models/{modelId}/features/{featureId}/inputs": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                modelId: components["parameters"]["modelId"];
                featureId: components["parameters"]["featureId"];
            };
            cookie?: never;
        };
        get?: never;
        /** Задать входные переменные фичи */
        put: operations["setFeatureScoreInputs"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scoring-models/{modelId}/products/{productId}/ranking": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                modelId: components["parameters"]["modelId"];
                productId: components["parameters"]["productId"];
            };
            cookie?: never;
        };
        /** Ранжирование фич продукта по модели (PR-01…PR-03) */
        get: operations["getRanking"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products/{productId}/roadmap/items": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                productId: components["parameters"]["productId"];
            };
            cookie?: never;
        };
        /** Элементы roadmap (внутренняя аудитория) */
        get: operations["listRoadmapItems"];
        put?: never;
        /** Создать элемент roadmap */
        post: operations["createRoadmapItem"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products/{productId}/roadmap/timeline": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                productId: components["parameters"]["productId"];
            };
            cookie?: never;
        };
        /** Timeline (RM-01); срез по аудитории субъекта (RM-02) */
        get: operations["getRoadmapTimeline"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products/{productId}/roadmap/now-next-later": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                productId: components["parameters"]["productId"];
            };
            cookie?: never;
        };
        /** Now/Next/Later (RM-01) */
        get: operations["getRoadmapNowNextLater"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products/{productId}/roadmap/by-release": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                productId: components["parameters"]["productId"];
            };
            cookie?: never;
        };
        /** По релизам (RM-01) */
        get: operations["getRoadmapByRelease"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products/{productId}/releases": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                productId: components["parameters"]["productId"];
            };
            cookie?: never;
        };
        /** Релизы продукта */
        get: operations["listReleases"];
        put?: never;
        /** Создать релиз */
        post: operations["createRelease"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/roadmap/items/{itemId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                itemId: components["parameters"]["itemId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Изменить элемент (даты — через change-dates) */
        patch: operations["updateRoadmapItem"];
        trace?: never;
    };
    "/roadmap/items/{itemId}/change-dates": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                itemId: components["parameters"]["itemId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Изменить даты с обязательной причиной (RM-03) */
        post: operations["changeRoadmapItemDates"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/roadmap/items/{itemId}/history": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                itemId: components["parameters"]["itemId"];
            };
            cookie?: never;
        };
        /** История изменений дат (RM-03) */
        get: operations["getRoadmapItemHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Problem: {
            type: string;
            title: string;
            status: number;
            detail?: string;
            field?: string;
        };
        CycleProblem: components["schemas"]["Problem"] & {
            /** @description Путь цикла f1 → f2 → … → f1 */
            cycle: string[];
        };
        Money: {
            /**
             * Format: int64
             * @description Минорные единицы
             */
            amount: number;
            currency: string;
        };
        Me: {
            subject: string;
            roles: string[];
            /** @enum {string} */
            audience: "internal" | "sales_safe";
            /** @enum {string} */
            all_products: "none" | "strategic" | "private";
            products: {
                [key: string]: "none" | "strategic" | "private";
            };
        };
        ProductInput: {
            key: string;
            name: string;
            /** @enum {string} */
            type: "security" | "infrastructure" | "platform" | "other";
            owner?: string;
            /** @enum {string} */
            lifecycle?: "idea" | "active" | "sunset" | "retired";
            ssdlc_certified?: boolean;
            hub_manual?: boolean;
        };
        Product: components["schemas"]["ProductInput"] & {
            /** Format: uuid */
            id: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        Capability: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            product_id: string;
            name: string;
        };
        FeatureInput: {
            /** Format: uuid */
            capability_id?: string;
            name?: string;
            /** @enum {string} */
            status?: "idea" | "discovery" | "planned" | "in_progress" | "done" | "rejected";
            /** Format: date */
            planned_date?: string;
            external_key?: string;
        };
        Feature: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            product_id: string;
            /** Format: uuid */
            capability_id?: string;
            name: string;
            /** @enum {string} */
            status: "idea" | "discovery" | "planned" | "in_progress" | "done" | "rejected";
            own_value: components["schemas"]["Money"];
            /** Format: date */
            planned_date?: string | null;
            affected: boolean;
            /** Format: uuid */
            affected_by?: string;
            /** Format: date */
            implied_date?: string | null;
            external_key?: string;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
        };
        Requirement: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            product_id: string;
            /** Format: uuid */
            feature_id: string;
            text: string;
        };
        FeatureValue: {
            /** Format: uuid */
            feature_id: string;
            /** Format: uuid */
            product_id: string;
            own_value: components["schemas"]["Money"];
            derived_value: components["schemas"]["Money"];
            total_value: components["schemas"]["Money"];
            /** Format: date-time */
            computed_at: string;
        };
        LinkInput: {
            /** @enum {string} */
            type: "integration" | "shared_component" | "commercial" | "bundled";
            /** Format: uuid */
            from_product_id?: string;
            /** Format: uuid */
            to_product_id?: string;
            /** Format: uuid */
            from_feature_id?: string;
            /** Format: uuid */
            to_feature_id?: string;
            /** @enum {string} */
            criticality: "blocks" | "accelerates" | "desirable";
            /** Format: uuid */
            contract_id?: string;
        };
        Link: components["schemas"]["LinkInput"] & {
            /** Format: uuid */
            id: string;
            /** Format: date-time */
            created_at: string;
        };
        HubInfo: {
            /** Format: uuid */
            product_id: string;
            in_degree: number;
            manual: boolean;
            computed: boolean;
        };
        VersionPair: {
            provider_version: string;
            consumer_version: string;
            compatible: boolean;
        };
        ContractInput: {
            name: string;
            /** Format: uuid */
            provider_product_id: string;
            /** Format: uuid */
            consumer_product_id: string;
            provider_feature_ids?: string[];
            consumer_feature_ids?: string[];
            interface_version?: string;
            owner?: string;
            /** @enum {string} */
            status?: "draft" | "active" | "deprecated";
            /** @enum {string} */
            criticality: "blocks" | "accelerates" | "desirable";
            compatibility?: components["schemas"]["VersionPair"][];
        };
        Contract: components["schemas"]["ContractInput"] & {
            /** Format: uuid */
            id: string;
            signal_value: components["schemas"]["Money"];
            /** Format: date */
            ready_date?: string | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        AffectedFeature: {
            /** Format: uuid */
            feature_id: string;
            /** Format: uuid */
            product_id: string;
            /** Format: date */
            planned_date?: string | null;
            /** Format: date */
            implied_date?: string | null;
            /** Format: uuid */
            via_feature: string;
            depth: number;
        };
        ShiftResult: {
            /** Format: uuid */
            source_feature: string;
            /** Format: date */
            old_date?: string | null;
            /** Format: date */
            new_date: string;
            affected: components["schemas"]["AffectedFeature"][];
            contracts: string[];
            commitments: string[];
        };
        StrategicFeature: {
            /** Format: uuid */
            id: string;
            name: string;
            status: string;
            total_value: components["schemas"]["Money"];
            /** Format: date */
            planned_date?: string | null;
            affected: boolean;
        };
        StrategicSlice: {
            product: components["schemas"]["Product"];
            features: components["schemas"]["StrategicFeature"][];
            contracts: components["schemas"]["Contract"][];
        };
        GraphSettings: {
            /** @description Коэффициенты критичности как десятичные строки */
            coefficients: {
                [key: string]: string;
            };
        };
        AuditVerifyResult: {
            /** Format: int64 */
            checked: number;
            ok: boolean;
            /** Format: int64 */
            broken_seq?: number;
            reason?: string;
        };
        SignalInput: {
            /** @enum {string} */
            source: "crm" | "service_desk" | "manual" | "import";
            text: string;
            external_key?: string;
            account_id?: string;
            deal_id?: string;
            version?: string;
            segment?: string;
            deal_amount?: components["schemas"]["Money"];
            account_arr?: components["schemas"]["Money"];
            blocks_deal?: boolean;
        };
        Signal: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            product_id: string;
            /** @enum {string} */
            source: "crm" | "service_desk" | "manual" | "import";
            text: string;
            external_key?: string;
            account_id?: string;
            deal_id?: string;
            version?: string;
            segment?: string;
            weight: components["schemas"]["Money"];
            account_arr: components["schemas"]["Money"];
            blocks_deal: boolean;
            /** @enum {string} */
            status: "new" | "in_review" | "linked" | "rejected" | "merged";
            /** Format: date */
            due_date?: string | null;
            /** Format: uuid */
            feature_id?: string;
            /** Format: uuid */
            contract_id?: string;
            created_by: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        ImportResult: {
            imported: number;
            skipped: {
                [key: string]: string;
            };
        };
        ScoringModelInput: {
            /**
             * Format: uuid
             * @description Пусто — портфельная модель
             */
            product_id?: string;
            name: string;
            /** @enum {string} */
            type: "rice" | "wsjf" | "custom";
            formula?: string;
            inputs?: string[];
        };
        ScoringModel: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            product_id?: string;
            name: string;
            /** @enum {string} */
            type: "rice" | "wsjf" | "custom";
            formula: string;
            inputs: string[];
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        ScoreComponent: {
            name: string;
            value: string;
            system: boolean;
        };
        ScoreResult: {
            /** Format: uuid */
            model_id: string;
            /** Format: uuid */
            feature_id: string;
            /** Format: uuid */
            product_id: string;
            /** @description Десятичное число строкой */
            score: string;
            components: components["schemas"]["ScoreComponent"][];
            explanation: string;
        };
        RoadmapItemInput: {
            /** Format: uuid */
            feature_id?: string;
            title?: string;
            /** @enum {string} */
            bucket?: "now" | "next" | "later";
            /** Format: date */
            start_date?: string;
            /** Format: date */
            end_date?: string;
            /** Format: uuid */
            release_id?: string;
            /** @enum {string} */
            audience?: "internal" | "sales_safe";
            /** @enum {string} */
            status?: "planned" | "in_progress" | "done" | "cancelled";
        };
        RoadmapItem: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            product_id: string;
            /** Format: uuid */
            feature_id?: string;
            title: string;
            /** @enum {string} */
            bucket: "now" | "next" | "later";
            /** Format: date */
            start_date?: string | null;
            /** Format: date */
            end_date?: string | null;
            /** Format: uuid */
            release_id?: string;
            /** @enum {string} */
            audience: "internal" | "sales_safe";
            /** @enum {string} */
            status: "planned" | "in_progress" | "done" | "cancelled";
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        SalesSafeItem: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            product_id: string;
            title: string;
            /** @enum {string} */
            bucket: "now" | "next" | "later";
            /** Format: date */
            start_date?: string | null;
            /** Format: date */
            end_date?: string | null;
            /** Format: uuid */
            release_id?: string;
        };
        RoadmapGroup: {
            items?: components["schemas"]["RoadmapItem"][];
            sales_safe?: components["schemas"]["SalesSafeItem"][];
        };
        RoadmapTimeline: {
            /** Format: uuid */
            product_id: string;
            /** @enum {string} */
            audience: "internal" | "sales_safe";
            items?: components["schemas"]["RoadmapItem"][];
            sales_safe?: components["schemas"]["SalesSafeItem"][];
        };
        RoadmapNowNextLater: {
            /** Format: uuid */
            product_id: string;
            /** @enum {string} */
            audience: "internal" | "sales_safe";
            now: components["schemas"]["RoadmapGroup"];
            next: components["schemas"]["RoadmapGroup"];
            later: components["schemas"]["RoadmapGroup"];
        };
        ReleaseGroup: {
            release: components["schemas"]["Release"];
            items?: components["schemas"]["RoadmapItem"][];
            sales_safe?: components["schemas"]["SalesSafeItem"][];
        };
        RoadmapByRelease: {
            /** Format: uuid */
            product_id: string;
            /** @enum {string} */
            audience: "internal" | "sales_safe";
            releases: components["schemas"]["ReleaseGroup"][];
            unassigned: components["schemas"]["RoadmapGroup"];
        };
        ReleaseInput: {
            name: string;
            version: string;
            /** Format: date */
            planned_date?: string;
            /** @enum {string} */
            status?: "planned" | "released" | "eol";
        };
        Release: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            product_id: string;
            name: string;
            version: string;
            /** Format: date */
            planned_date?: string | null;
            /** @enum {string} */
            status: "planned" | "released" | "eol";
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        DateChange: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            item_id: string;
            /** Format: uuid */
            product_id: string;
            /** Format: date */
            old_start?: string | null;
            /** Format: date */
            old_end?: string | null;
            /** Format: date */
            new_start?: string | null;
            /** Format: date */
            new_end?: string | null;
            reason: string;
            actor: string;
            /** Format: date-time */
            at: string;
            /** Format: uuid */
            event_id?: string;
        };
    };
    responses: {
        /** @description Ошибка */
        Problem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        productId: string;
        featureId: string;
        signalId: string;
        modelId: string;
        itemId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    listProducts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Product"][];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    createProduct: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProductInput"];
            };
        };
        responses: {
            /** @description Создано */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Product"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getProduct: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                productId: components["parameters"]["productId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Product"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    updateProduct: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                productId: components["parameters"]["productId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProductInput"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Product"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getStrategicSlice: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                productId: components["parameters"]["productId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StrategicSlice"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    createCapability: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                productId: components["parameters"]["productId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name: string;
                };
            };
        };
        responses: {
            /** @description Создано */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Capability"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    listFeatures: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                productId: components["parameters"]["productId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Feature"][];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    createFeature: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                productId: components["parameters"]["productId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeatureInput"];
            };
        };
        responses: {
            /** @description Создано */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Feature"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    listFeatureValues: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                productId: components["parameters"]["productId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeatureValue"][];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getFeature: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                featureId: components["parameters"]["featureId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Feature"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    updateFeature: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                featureId: components["parameters"]["featureId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeatureInput"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Feature"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    createRequirement: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                featureId: components["parameters"]["featureId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    text: string;
                };
            };
        };
        responses: {
            /** @description Создано */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Requirement"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    shiftFeatureDate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                featureId: components["parameters"]["featureId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: date */
                    planned_date: string;
                    reason: string;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShiftResult"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getFeatureValue: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                featureId: components["parameters"]["featureId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeatureValue"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    listLinks: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Link"][];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    createLink: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LinkInput"];
            };
        };
        responses: {
            /** @description Создано */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Link"];
                };
            };
            /** @description Цикл в графе зависимостей фич */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["CycleProblem"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    deleteLink: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                linkId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Удалено */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Problem"];
        };
    };
    listHubs: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HubInfo"][];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    listContracts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Contract"][];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    createContract: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ContractInput"];
            };
        };
        responses: {
            /** @description Создано */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Contract"];
                };
            };
            /** @description Цикл в графе зависимостей фич */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["CycleProblem"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getContract: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                contractId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Contract"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    updateContract: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                contractId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ContractInput"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Contract"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getGraphSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GraphSettings"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    updateGraphSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GraphSettings"];
            };
        };
        responses: {
            /** @description OK */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Problem"];
        };
    };
    verifyAudit: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditVerifyResult"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    listSignals: {
        parameters: {
            query?: {
                status?: ("new" | "in_review" | "linked" | "rejected" | "merged")[];
                feature_id?: string;
            };
            header?: never;
            path: {
                productId: components["parameters"]["productId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Signal"][];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    ingestSignal: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                productId: components["parameters"]["productId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignalInput"];
            };
        };
        responses: {
            /** @description Создано */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Signal"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    triageQueue: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                productId: components["parameters"]["productId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Signal"][];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    importSignalsFromCRM: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportResult"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getSignal: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                signalId: components["parameters"]["signalId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Signal"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    triageSignal: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                signalId: components["parameters"]["signalId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @enum {string} */
                    status: "new" | "in_review" | "rejected";
                    /** Format: date */
                    due_date?: string;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Signal"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    linkSignal: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                signalId: components["parameters"]["signalId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: uuid */
                    feature_id?: string;
                    /** Format: uuid */
                    contract_id?: string;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Signal"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    listScoringModels: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScoringModel"][];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    createScoringModel: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScoringModelInput"];
            };
        };
        responses: {
            /** @description Создано */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScoringModel"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    updateScoringModel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                modelId: components["parameters"]["modelId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScoringModelInput"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScoringModel"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    setFeatureScoreInputs: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                modelId: components["parameters"]["modelId"];
                featureId: components["parameters"]["featureId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    values: {
                        [key: string]: string;
                    };
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScoreResult"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getRanking: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                modelId: components["parameters"]["modelId"];
                productId: components["parameters"]["productId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScoreResult"][];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    listRoadmapItems: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                productId: components["parameters"]["productId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoadmapItem"][];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    createRoadmapItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                productId: components["parameters"]["productId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoadmapItemInput"];
            };
        };
        responses: {
            /** @description Создано */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoadmapItem"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getRoadmapTimeline: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                productId: components["parameters"]["productId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoadmapTimeline"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getRoadmapNowNextLater: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                productId: components["parameters"]["productId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoadmapNowNextLater"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getRoadmapByRelease: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                productId: components["parameters"]["productId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoadmapByRelease"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    listReleases: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                productId: components["parameters"]["productId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Release"][];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    createRelease: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                productId: components["parameters"]["productId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReleaseInput"];
            };
        };
        responses: {
            /** @description Создано */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Release"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    updateRoadmapItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                itemId: components["parameters"]["itemId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoadmapItemInput"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoadmapItem"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    changeRoadmapItemDates: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                itemId: components["parameters"]["itemId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: date */
                    start_date?: string;
                    /** Format: date */
                    end_date?: string;
                    reason: string;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoadmapItem"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getRoadmapItemHistory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                itemId: components["parameters"]["itemId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DateChange"][];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
}
