import type { components } from './schema'

type S = components['schemas']
export type Me = S['Me']
export type Product = S['Product']
export type Feature = S['Feature']
export type FeatureValue = S['FeatureValue']
export type Link = S['Link']
export type HubInfo = S['HubInfo']
export type Contract = S['Contract']
export type StrategicSlice = S['StrategicSlice']
export type Signal = S['Signal']
export type ShiftResult = S['ShiftResult']
export type RoadmapItem = S['RoadmapItem']
export type SalesSafeItem = S['SalesSafeItem']
export type RoadmapTimeline = S['RoadmapTimeline']
export type RoadmapNowNextLater = S['RoadmapNowNextLater']
export type RoadmapByRelease = S['RoadmapByRelease']
export type Release = S['Release']
export type DateChange = S['DateChange']
export type AuditVerifyResult = S['AuditVerifyResult']
export type Money = S['Money']
export type AccessLevel = Me['all_products']
export type LinkType = Link['type']
export type Criticality = Link['criticality']
export type Lifecycle = NonNullable<Product['lifecycle']>
