// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: decisions.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const eventProcessed = `-- name: EventProcessed :one
SELECT EXISTS (SELECT 1 FROM decisions.processed_events WHERE event_id = $1)
`

func (q *Queries) EventProcessed(ctx context.Context, eventID uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, eventProcessed, eventID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getRecord = `-- name: GetRecord :one
SELECT id, product_id, title, context, snapshot, options, chosen_key, rationale, expected_effect, review_date, status, superseded_by, links, page_id, author, created_at, updated_at, effect_metric, effect_value, effect_period, review FROM decisions.records WHERE id = $1
`

func (q *Queries) GetRecord(ctx context.Context, id uuid.UUID) (DecisionsRecord, error) {
	row := q.db.QueryRow(ctx, getRecord, id)
	var i DecisionsRecord
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Title,
		&i.Context,
		&i.Snapshot,
		&i.Options,
		&i.ChosenKey,
		&i.Rationale,
		&i.ExpectedEffect,
		&i.ReviewDate,
		&i.Status,
		&i.SupersededBy,
		&i.Links,
		&i.PageID,
		&i.Author,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EffectMetric,
		&i.EffectValue,
		&i.EffectPeriod,
		&i.Review,
	)
	return i, err
}

const listRecords = `-- name: ListRecords :many
SELECT id, product_id, title, context, snapshot, options, chosen_key, rationale, expected_effect, review_date, status, superseded_by, links, page_id, author, created_at, updated_at, effect_metric, effect_value, effect_period, review FROM decisions.records
WHERE (NOT $1::bool OR product_id IS NOT DISTINCT FROM $2::uuid)
  AND ($3::text = '' OR status = $3::text)
  AND ($4::jsonb IS NULL OR links @> $4::jsonb)
ORDER BY created_at, id
`

type ListRecordsParams struct {
	HasProduct bool
	ProductID  uuid.NullUUID
	Status     string
	Link       []byte
}

func (q *Queries) ListRecords(ctx context.Context, arg ListRecordsParams) ([]DecisionsRecord, error) {
	rows, err := q.db.Query(ctx, listRecords,
		arg.HasProduct,
		arg.ProductID,
		arg.Status,
		arg.Link,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DecisionsRecord
	for rows.Next() {
		var i DecisionsRecord
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.Title,
			&i.Context,
			&i.Snapshot,
			&i.Options,
			&i.ChosenKey,
			&i.Rationale,
			&i.ExpectedEffect,
			&i.ReviewDate,
			&i.Status,
			&i.SupersededBy,
			&i.Links,
			&i.PageID,
			&i.Author,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EffectMetric,
			&i.EffectValue,
			&i.EffectPeriod,
			&i.Review,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecordsDueForReview = `-- name: ListRecordsDueForReview :many
SELECT id, product_id, title, context, snapshot, options, chosen_key, rationale, expected_effect, review_date, status, superseded_by, links, page_id, author, created_at, updated_at, effect_metric, effect_value, effect_period, review FROM decisions.records
WHERE review IS NULL AND review_date IS NOT NULL AND review_date <= $1::date
  AND status = 'accepted'
ORDER BY review_date, id
`

// DA-06: решения с наступившей датой ревизии, по которым ревизии ещё не было.
func (q *Queries) ListRecordsDueForReview(ctx context.Context, on pgtype.Date) ([]DecisionsRecord, error) {
	rows, err := q.db.Query(ctx, listRecordsDueForReview, on)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DecisionsRecord
	for rows.Next() {
		var i DecisionsRecord
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.Title,
			&i.Context,
			&i.Snapshot,
			&i.Options,
			&i.ChosenKey,
			&i.Rationale,
			&i.ExpectedEffect,
			&i.ReviewDate,
			&i.Status,
			&i.SupersededBy,
			&i.Links,
			&i.PageID,
			&i.Author,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EffectMetric,
			&i.EffectValue,
			&i.EffectPeriod,
			&i.Review,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markEventProcessed = `-- name: MarkEventProcessed :exec
INSERT INTO decisions.processed_events (event_id) VALUES ($1) ON CONFLICT (event_id) DO NOTHING
`

func (q *Queries) MarkEventProcessed(ctx context.Context, eventID uuid.UUID) error {
	_, err := q.db.Exec(ctx, markEventProcessed, eventID)
	return err
}

const upsertRecord = `-- name: UpsertRecord :exec
INSERT INTO decisions.records (id, product_id, title, context, snapshot, options, chosen_key, rationale, expected_effect, review_date, status, superseded_by, links, page_id, author, created_at, updated_at, effect_metric, effect_value, effect_period, review)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21)
ON CONFLICT (id) DO UPDATE SET product_id = EXCLUDED.product_id, title = EXCLUDED.title, context = EXCLUDED.context,
  snapshot = EXCLUDED.snapshot, options = EXCLUDED.options, chosen_key = EXCLUDED.chosen_key, rationale = EXCLUDED.rationale,
  expected_effect = EXCLUDED.expected_effect, review_date = EXCLUDED.review_date, status = EXCLUDED.status,
  superseded_by = EXCLUDED.superseded_by, links = EXCLUDED.links, page_id = EXCLUDED.page_id, author = EXCLUDED.author,
  updated_at = EXCLUDED.updated_at, effect_metric = EXCLUDED.effect_metric, effect_value = EXCLUDED.effect_value,
  effect_period = EXCLUDED.effect_period, review = EXCLUDED.review
`

type UpsertRecordParams struct {
	ID             uuid.UUID
	ProductID      uuid.NullUUID
	Title          string
	Context        string
	Snapshot       []byte
	Options        []byte
	ChosenKey      string
	Rationale      string
	ExpectedEffect string
	ReviewDate     pgtype.Date
	Status         string
	SupersededBy   uuid.NullUUID
	Links          []byte
	PageID         string
	Author         string
	CreatedAt      time.Time
	UpdatedAt      time.Time
	EffectMetric   string
	EffectValue    string
	EffectPeriod   string
	Review         []byte
}

func (q *Queries) UpsertRecord(ctx context.Context, arg UpsertRecordParams) error {
	_, err := q.db.Exec(ctx, upsertRecord,
		arg.ID,
		arg.ProductID,
		arg.Title,
		arg.Context,
		arg.Snapshot,
		arg.Options,
		arg.ChosenKey,
		arg.Rationale,
		arg.ExpectedEffect,
		arg.ReviewDate,
		arg.Status,
		arg.SupersededBy,
		arg.Links,
		arg.PageID,
		arg.Author,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.EffectMetric,
		arg.EffectValue,
		arg.EffectPeriod,
		arg.Review,
	)
	return err
}
