// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type DecisionsProcessedEvent struct {
	EventID     uuid.UUID
	ProcessedAt time.Time
}

type DecisionsRecord struct {
	ID             uuid.UUID
	ProductID      uuid.NullUUID
	Title          string
	Context        string
	Snapshot       []byte
	Options        []byte
	ChosenKey      string
	Rationale      string
	ExpectedEffect string
	ReviewDate     pgtype.Date
	Status         string
	SupersededBy   uuid.NullUUID
	Links          []byte
	PageID         string
	Author         string
	CreatedAt      time.Time
	UpdatedAt      time.Time
}
