// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: graph.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const deleteLink = `-- name: DeleteLink :execrows
DELETE FROM portfoliograph.links WHERE id = $1
`

func (q *Queries) DeleteLink(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteLink, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getSettings = `-- name: GetSettings :one
SELECT coefficients FROM portfoliograph.settings WHERE id = 1
`

func (q *Queries) GetSettings(ctx context.Context) ([]byte, error) {
	row := q.db.QueryRow(ctx, getSettings)
	var coefficients []byte
	err := row.Scan(&coefficients)
	return coefficients, err
}

const listCapabilities = `-- name: ListCapabilities :many
SELECT id, product_id, name FROM portfoliograph.capabilities ORDER BY id
`

func (q *Queries) ListCapabilities(ctx context.Context) ([]PortfoliographCapability, error) {
	rows, err := q.db.Query(ctx, listCapabilities)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PortfoliographCapability
	for rows.Next() {
		var i PortfoliographCapability
		if err := rows.Scan(&i.ID, &i.ProductID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContracts = `-- name: ListContracts :many
SELECT id, name, provider_product_id, consumer_product_id, provider_feature_ids, consumer_feature_ids, interface_version, owner, status, criticality, compatibility, signal_value_amount, signal_value_currency, created_at, updated_at FROM portfoliograph.contracts ORDER BY id
`

func (q *Queries) ListContracts(ctx context.Context) ([]PortfoliographContract, error) {
	rows, err := q.db.Query(ctx, listContracts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PortfoliographContract
	for rows.Next() {
		var i PortfoliographContract
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ProviderProductID,
			&i.ConsumerProductID,
			&i.ProviderFeatureIds,
			&i.ConsumerFeatureIds,
			&i.InterfaceVersion,
			&i.Owner,
			&i.Status,
			&i.Criticality,
			&i.Compatibility,
			&i.SignalValueAmount,
			&i.SignalValueCurrency,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFeatureValues = `-- name: ListFeatureValues :many
SELECT feature_id, product_id, own_value_amount, own_value_currency, derived_value_amount, derived_value_currency, total_value_amount, total_value_currency, computed_at FROM portfoliograph.feature_values ORDER BY feature_id
`

func (q *Queries) ListFeatureValues(ctx context.Context) ([]PortfoliographFeatureValue, error) {
	rows, err := q.db.Query(ctx, listFeatureValues)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PortfoliographFeatureValue
	for rows.Next() {
		var i PortfoliographFeatureValue
		if err := rows.Scan(
			&i.FeatureID,
			&i.ProductID,
			&i.OwnValueAmount,
			&i.OwnValueCurrency,
			&i.DerivedValueAmount,
			&i.DerivedValueCurrency,
			&i.TotalValueAmount,
			&i.TotalValueCurrency,
			&i.ComputedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFeatures = `-- name: ListFeatures :many
SELECT id, product_id, capability_id, name, status, own_value_amount, own_value_currency, planned_date, affected, affected_by, implied_date, external_key, created_at, updated_at FROM portfoliograph.features ORDER BY id
`

func (q *Queries) ListFeatures(ctx context.Context) ([]PortfoliographFeature, error) {
	rows, err := q.db.Query(ctx, listFeatures)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PortfoliographFeature
	for rows.Next() {
		var i PortfoliographFeature
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.CapabilityID,
			&i.Name,
			&i.Status,
			&i.OwnValueAmount,
			&i.OwnValueCurrency,
			&i.PlannedDate,
			&i.Affected,
			&i.AffectedBy,
			&i.ImpliedDate,
			&i.ExternalKey,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLinks = `-- name: ListLinks :many
SELECT id, type, from_product_id, to_product_id, from_feature_id, to_feature_id, criticality, contract_id, created_at FROM portfoliograph.links ORDER BY id
`

func (q *Queries) ListLinks(ctx context.Context) ([]PortfoliographLink, error) {
	rows, err := q.db.Query(ctx, listLinks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PortfoliographLink
	for rows.Next() {
		var i PortfoliographLink
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.FromProductID,
			&i.ToProductID,
			&i.FromFeatureID,
			&i.ToFeatureID,
			&i.Criticality,
			&i.ContractID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProducts = `-- name: ListProducts :many
SELECT id, key, name, type, owner, lifecycle, ssdlc_certified, hub_manual, created_at, updated_at FROM portfoliograph.products ORDER BY id
`

func (q *Queries) ListProducts(ctx context.Context) ([]PortfoliographProduct, error) {
	rows, err := q.db.Query(ctx, listProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PortfoliographProduct
	for rows.Next() {
		var i PortfoliographProduct
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.Name,
			&i.Type,
			&i.Owner,
			&i.Lifecycle,
			&i.SsdlcCertified,
			&i.HubManual,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRequirements = `-- name: ListRequirements :many
SELECT id, product_id, feature_id, text FROM portfoliograph.requirements ORDER BY id
`

func (q *Queries) ListRequirements(ctx context.Context) ([]PortfoliographRequirement, error) {
	rows, err := q.db.Query(ctx, listRequirements)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PortfoliographRequirement
	for rows.Next() {
		var i PortfoliographRequirement
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.FeatureID,
			&i.Text,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertCapability = `-- name: UpsertCapability :exec
INSERT INTO portfoliograph.capabilities (id, product_id, name)
VALUES ($1, $2, $3)
ON CONFLICT (id) DO UPDATE SET product_id = EXCLUDED.product_id, name = EXCLUDED.name
`

type UpsertCapabilityParams struct {
	ID        uuid.UUID
	ProductID uuid.UUID
	Name      string
}

func (q *Queries) UpsertCapability(ctx context.Context, arg UpsertCapabilityParams) error {
	_, err := q.db.Exec(ctx, upsertCapability, arg.ID, arg.ProductID, arg.Name)
	return err
}

const upsertContract = `-- name: UpsertContract :exec
INSERT INTO portfoliograph.contracts (id, name, provider_product_id, consumer_product_id, provider_feature_ids, consumer_feature_ids,
  interface_version, owner, status, criticality, compatibility, signal_value_amount, signal_value_currency, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15)
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name, provider_product_id = EXCLUDED.provider_product_id, consumer_product_id = EXCLUDED.consumer_product_id,
  provider_feature_ids = EXCLUDED.provider_feature_ids, consumer_feature_ids = EXCLUDED.consumer_feature_ids,
  interface_version = EXCLUDED.interface_version, owner = EXCLUDED.owner, status = EXCLUDED.status,
  criticality = EXCLUDED.criticality, compatibility = EXCLUDED.compatibility,
  signal_value_amount = EXCLUDED.signal_value_amount, signal_value_currency = EXCLUDED.signal_value_currency,
  updated_at = EXCLUDED.updated_at
`

type UpsertContractParams struct {
	ID                  uuid.UUID
	Name                string
	ProviderProductID   uuid.UUID
	ConsumerProductID   uuid.UUID
	ProviderFeatureIds  []uuid.UUID
	ConsumerFeatureIds  []uuid.UUID
	InterfaceVersion    string
	Owner               string
	Status              string
	Criticality         string
	Compatibility       []byte
	SignalValueAmount   int64
	SignalValueCurrency string
	CreatedAt           time.Time
	UpdatedAt           time.Time
}

func (q *Queries) UpsertContract(ctx context.Context, arg UpsertContractParams) error {
	_, err := q.db.Exec(ctx, upsertContract,
		arg.ID,
		arg.Name,
		arg.ProviderProductID,
		arg.ConsumerProductID,
		arg.ProviderFeatureIds,
		arg.ConsumerFeatureIds,
		arg.InterfaceVersion,
		arg.Owner,
		arg.Status,
		arg.Criticality,
		arg.Compatibility,
		arg.SignalValueAmount,
		arg.SignalValueCurrency,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const upsertFeature = `-- name: UpsertFeature :exec
INSERT INTO portfoliograph.features (id, product_id, capability_id, name, status, own_value_amount, own_value_currency,
  planned_date, affected, affected_by, implied_date, external_key, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
ON CONFLICT (id) DO UPDATE SET
  product_id = EXCLUDED.product_id, capability_id = EXCLUDED.capability_id, name = EXCLUDED.name,
  status = EXCLUDED.status, own_value_amount = EXCLUDED.own_value_amount, own_value_currency = EXCLUDED.own_value_currency,
  planned_date = EXCLUDED.planned_date, affected = EXCLUDED.affected, affected_by = EXCLUDED.affected_by,
  implied_date = EXCLUDED.implied_date, external_key = EXCLUDED.external_key, updated_at = EXCLUDED.updated_at
`

type UpsertFeatureParams struct {
	ID               uuid.UUID
	ProductID        uuid.UUID
	CapabilityID     uuid.NullUUID
	Name             string
	Status           string
	OwnValueAmount   int64
	OwnValueCurrency string
	PlannedDate      pgtype.Date
	Affected         bool
	AffectedBy       uuid.NullUUID
	ImpliedDate      pgtype.Date
	ExternalKey      string
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

func (q *Queries) UpsertFeature(ctx context.Context, arg UpsertFeatureParams) error {
	_, err := q.db.Exec(ctx, upsertFeature,
		arg.ID,
		arg.ProductID,
		arg.CapabilityID,
		arg.Name,
		arg.Status,
		arg.OwnValueAmount,
		arg.OwnValueCurrency,
		arg.PlannedDate,
		arg.Affected,
		arg.AffectedBy,
		arg.ImpliedDate,
		arg.ExternalKey,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const upsertFeatureValue = `-- name: UpsertFeatureValue :exec
INSERT INTO portfoliograph.feature_values (feature_id, product_id, own_value_amount, own_value_currency,
  derived_value_amount, derived_value_currency, total_value_amount, total_value_currency, computed_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT (feature_id) DO UPDATE SET
  product_id = EXCLUDED.product_id, own_value_amount = EXCLUDED.own_value_amount, own_value_currency = EXCLUDED.own_value_currency,
  derived_value_amount = EXCLUDED.derived_value_amount, derived_value_currency = EXCLUDED.derived_value_currency,
  total_value_amount = EXCLUDED.total_value_amount, total_value_currency = EXCLUDED.total_value_currency,
  computed_at = EXCLUDED.computed_at
`

type UpsertFeatureValueParams struct {
	FeatureID            uuid.UUID
	ProductID            uuid.UUID
	OwnValueAmount       int64
	OwnValueCurrency     string
	DerivedValueAmount   int64
	DerivedValueCurrency string
	TotalValueAmount     int64
	TotalValueCurrency   string
	ComputedAt           time.Time
}

func (q *Queries) UpsertFeatureValue(ctx context.Context, arg UpsertFeatureValueParams) error {
	_, err := q.db.Exec(ctx, upsertFeatureValue,
		arg.FeatureID,
		arg.ProductID,
		arg.OwnValueAmount,
		arg.OwnValueCurrency,
		arg.DerivedValueAmount,
		arg.DerivedValueCurrency,
		arg.TotalValueAmount,
		arg.TotalValueCurrency,
		arg.ComputedAt,
	)
	return err
}

const upsertLink = `-- name: UpsertLink :exec
INSERT INTO portfoliograph.links (id, type, from_product_id, to_product_id, from_feature_id, to_feature_id, criticality, contract_id, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT (id) DO UPDATE SET
  type = EXCLUDED.type, from_product_id = EXCLUDED.from_product_id, to_product_id = EXCLUDED.to_product_id,
  from_feature_id = EXCLUDED.from_feature_id, to_feature_id = EXCLUDED.to_feature_id,
  criticality = EXCLUDED.criticality, contract_id = EXCLUDED.contract_id
`

type UpsertLinkParams struct {
	ID            uuid.UUID
	Type          string
	FromProductID uuid.UUID
	ToProductID   uuid.UUID
	FromFeatureID uuid.NullUUID
	ToFeatureID   uuid.NullUUID
	Criticality   string
	ContractID    uuid.NullUUID
	CreatedAt     time.Time
}

func (q *Queries) UpsertLink(ctx context.Context, arg UpsertLinkParams) error {
	_, err := q.db.Exec(ctx, upsertLink,
		arg.ID,
		arg.Type,
		arg.FromProductID,
		arg.ToProductID,
		arg.FromFeatureID,
		arg.ToFeatureID,
		arg.Criticality,
		arg.ContractID,
		arg.CreatedAt,
	)
	return err
}

const upsertProduct = `-- name: UpsertProduct :exec
INSERT INTO portfoliograph.products (id, key, name, type, owner, lifecycle, ssdlc_certified, hub_manual, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
ON CONFLICT (id) DO UPDATE SET
  key = EXCLUDED.key, name = EXCLUDED.name, type = EXCLUDED.type, owner = EXCLUDED.owner,
  lifecycle = EXCLUDED.lifecycle, ssdlc_certified = EXCLUDED.ssdlc_certified,
  hub_manual = EXCLUDED.hub_manual, updated_at = EXCLUDED.updated_at
`

type UpsertProductParams struct {
	ID             uuid.UUID
	Key            string
	Name           string
	Type           string
	Owner          string
	Lifecycle      string
	SsdlcCertified bool
	HubManual      bool
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

func (q *Queries) UpsertProduct(ctx context.Context, arg UpsertProductParams) error {
	_, err := q.db.Exec(ctx, upsertProduct,
		arg.ID,
		arg.Key,
		arg.Name,
		arg.Type,
		arg.Owner,
		arg.Lifecycle,
		arg.SsdlcCertified,
		arg.HubManual,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const upsertRequirement = `-- name: UpsertRequirement :exec
INSERT INTO portfoliograph.requirements (id, product_id, feature_id, text)
VALUES ($1, $2, $3, $4)
ON CONFLICT (id) DO UPDATE SET product_id = EXCLUDED.product_id, feature_id = EXCLUDED.feature_id, text = EXCLUDED.text
`

type UpsertRequirementParams struct {
	ID        uuid.UUID
	ProductID uuid.UUID
	FeatureID uuid.UUID
	Text      string
}

func (q *Queries) UpsertRequirement(ctx context.Context, arg UpsertRequirementParams) error {
	_, err := q.db.Exec(ctx, upsertRequirement,
		arg.ID,
		arg.ProductID,
		arg.FeatureID,
		arg.Text,
	)
	return err
}

const upsertSettings = `-- name: UpsertSettings :exec
INSERT INTO portfoliograph.settings (id, coefficients, updated_at) VALUES (1, $1, $2)
ON CONFLICT (id) DO UPDATE SET coefficients = EXCLUDED.coefficients, updated_at = EXCLUDED.updated_at
`

type UpsertSettingsParams struct {
	Coefficients []byte
	UpdatedAt    time.Time
}

func (q *Queries) UpsertSettings(ctx context.Context, arg UpsertSettingsParams) error {
	_, err := q.db.Exec(ctx, upsertSettings, arg.Coefficients, arg.UpdatedAt)
	return err
}
