// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type PortfoliographCapability struct {
	ID        uuid.UUID
	ProductID uuid.UUID
	Name      string
}

type PortfoliographContract struct {
	ID                  uuid.UUID
	Name                string
	ProviderProductID   uuid.UUID
	ConsumerProductID   uuid.UUID
	ProviderFeatureIds  []uuid.UUID
	ConsumerFeatureIds  []uuid.UUID
	InterfaceVersion    string
	Owner               string
	Status              string
	Criticality         string
	Compatibility       []byte
	SignalValueAmount   int64
	SignalValueCurrency string
	CreatedAt           time.Time
	UpdatedAt           time.Time
}

type PortfoliographFeature struct {
	ID               uuid.UUID
	ProductID        uuid.UUID
	CapabilityID     uuid.NullUUID
	Name             string
	Status           string
	OwnValueAmount   int64
	OwnValueCurrency string
	PlannedDate      pgtype.Date
	Affected         bool
	AffectedBy       uuid.NullUUID
	ImpliedDate      pgtype.Date
	ExternalKey      string
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

type PortfoliographFeatureValue struct {
	FeatureID            uuid.UUID
	ProductID            uuid.UUID
	OwnValueAmount       int64
	OwnValueCurrency     string
	DerivedValueAmount   int64
	DerivedValueCurrency string
	TotalValueAmount     int64
	TotalValueCurrency   string
	ComputedAt           time.Time
}

type PortfoliographLink struct {
	ID            uuid.UUID
	Type          string
	FromProductID uuid.UUID
	ToProductID   uuid.UUID
	FromFeatureID uuid.NullUUID
	ToFeatureID   uuid.NullUUID
	Criticality   string
	ContractID    uuid.NullUUID
	CreatedAt     time.Time
}

type PortfoliographProduct struct {
	ID             uuid.UUID
	Key            string
	Name           string
	Type           string
	Owner          string
	Lifecycle      string
	SsdlcCertified bool
	HubManual      bool
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type PortfoliographRequirement struct {
	ID        uuid.UUID
	ProductID uuid.UUID
	FeatureID uuid.UUID
	Text      string
}

type PortfoliographSetting struct {
	ID           int16
	Coefficients []byte
	UpdatedAt    time.Time
}
