// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type RoadmapDateHistory struct {
	Seq       int64
	ID        uuid.UUID
	ItemID    uuid.UUID
	ProductID uuid.UUID
	OldStart  pgtype.Date
	OldEnd    pgtype.Date
	NewStart  pgtype.Date
	NewEnd    pgtype.Date
	Reason    string
	Actor     string
	At        time.Time
	EventID   uuid.NullUUID
}

type RoadmapItem struct {
	ID           uuid.UUID
	ProductID    uuid.UUID
	FeatureID    uuid.NullUUID
	Title        string
	Bucket       string
	StartDate    pgtype.Date
	EndDate      pgtype.Date
	ReleaseID    uuid.NullUUID
	Audience     string
	Status       string
	Kind         string
	CommitmentID uuid.NullUUID
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type RoadmapProcessedEvent struct {
	EventID     uuid.UUID
	ProcessedAt time.Time
}

type RoadmapRelease struct {
	ID            uuid.UUID
	ProductID     uuid.UUID
	Name          string
	Version       string
	PlannedDate   pgtype.Date
	Status        string
	Branch        string
	BaseReleaseID uuid.NullUUID
	FeatureIds    []uuid.UUID
	ReleaseNotes  string
	Eol           pgtype.Date
	CreatedAt     time.Time
	UpdatedAt     time.Time
}
