// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: roadmap.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const eventProcessed = `-- name: EventProcessed :one
SELECT EXISTS (SELECT 1 FROM roadmap.processed_events WHERE event_id = $1)
`

func (q *Queries) EventProcessed(ctx context.Context, eventID uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, eventProcessed, eventID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getItem = `-- name: GetItem :one
SELECT id, product_id, feature_id, title, bucket, start_date, end_date, release_id, audience, status, kind, commitment_id, created_at, updated_at, launch_tier, launch_date FROM roadmap.items WHERE id = $1
`

func (q *Queries) GetItem(ctx context.Context, id uuid.UUID) (RoadmapItem, error) {
	row := q.db.QueryRow(ctx, getItem, id)
	var i RoadmapItem
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.FeatureID,
		&i.Title,
		&i.Bucket,
		&i.StartDate,
		&i.EndDate,
		&i.ReleaseID,
		&i.Audience,
		&i.Status,
		&i.Kind,
		&i.CommitmentID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LaunchTier,
		&i.LaunchDate,
	)
	return i, err
}

const getItemByCommitment = `-- name: GetItemByCommitment :one
SELECT id, product_id, feature_id, title, bucket, start_date, end_date, release_id, audience, status, kind, commitment_id, created_at, updated_at, launch_tier, launch_date FROM roadmap.items WHERE commitment_id = $1 ORDER BY created_at, id LIMIT 1
`

func (q *Queries) GetItemByCommitment(ctx context.Context, commitmentID uuid.NullUUID) (RoadmapItem, error) {
	row := q.db.QueryRow(ctx, getItemByCommitment, commitmentID)
	var i RoadmapItem
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.FeatureID,
		&i.Title,
		&i.Bucket,
		&i.StartDate,
		&i.EndDate,
		&i.ReleaseID,
		&i.Audience,
		&i.Status,
		&i.Kind,
		&i.CommitmentID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LaunchTier,
		&i.LaunchDate,
	)
	return i, err
}

const getRelease = `-- name: GetRelease :one
SELECT id, product_id, name, version, planned_date, status, branch, base_release_id, feature_ids, release_notes, eol, created_at, updated_at FROM roadmap.releases WHERE id = $1
`

func (q *Queries) GetRelease(ctx context.Context, id uuid.UUID) (RoadmapRelease, error) {
	row := q.db.QueryRow(ctx, getRelease, id)
	var i RoadmapRelease
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Name,
		&i.Version,
		&i.PlannedDate,
		&i.Status,
		&i.Branch,
		&i.BaseReleaseID,
		&i.FeatureIds,
		&i.ReleaseNotes,
		&i.Eol,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertDateChange = `-- name: InsertDateChange :exec
INSERT INTO roadmap.date_history (id, item_id, product_id, old_start, old_end, new_start, new_end, reason, actor, at, event_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
`

type InsertDateChangeParams struct {
	ID        uuid.UUID
	ItemID    uuid.UUID
	ProductID uuid.UUID
	OldStart  pgtype.Date
	OldEnd    pgtype.Date
	NewStart  pgtype.Date
	NewEnd    pgtype.Date
	Reason    string
	Actor     string
	At        time.Time
	EventID   uuid.NullUUID
}

func (q *Queries) InsertDateChange(ctx context.Context, arg InsertDateChangeParams) error {
	_, err := q.db.Exec(ctx, insertDateChange,
		arg.ID,
		arg.ItemID,
		arg.ProductID,
		arg.OldStart,
		arg.OldEnd,
		arg.NewStart,
		arg.NewEnd,
		arg.Reason,
		arg.Actor,
		arg.At,
		arg.EventID,
	)
	return err
}

const listDateHistory = `-- name: ListDateHistory :many
SELECT seq, id, item_id, product_id, old_start, old_end, new_start, new_end, reason, actor, at, event_id FROM roadmap.date_history WHERE item_id = $1 ORDER BY seq
`

func (q *Queries) ListDateHistory(ctx context.Context, itemID uuid.UUID) ([]RoadmapDateHistory, error) {
	rows, err := q.db.Query(ctx, listDateHistory, itemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RoadmapDateHistory
	for rows.Next() {
		var i RoadmapDateHistory
		if err := rows.Scan(
			&i.Seq,
			&i.ID,
			&i.ItemID,
			&i.ProductID,
			&i.OldStart,
			&i.OldEnd,
			&i.NewStart,
			&i.NewEnd,
			&i.Reason,
			&i.Actor,
			&i.At,
			&i.EventID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listItemsByFeature = `-- name: ListItemsByFeature :many
SELECT id, product_id, feature_id, title, bucket, start_date, end_date, release_id, audience, status, kind, commitment_id, created_at, updated_at, launch_tier, launch_date FROM roadmap.items WHERE feature_id = $1 ORDER BY created_at, id
`

func (q *Queries) ListItemsByFeature(ctx context.Context, featureID uuid.NullUUID) ([]RoadmapItem, error) {
	rows, err := q.db.Query(ctx, listItemsByFeature, featureID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RoadmapItem
	for rows.Next() {
		var i RoadmapItem
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.FeatureID,
			&i.Title,
			&i.Bucket,
			&i.StartDate,
			&i.EndDate,
			&i.ReleaseID,
			&i.Audience,
			&i.Status,
			&i.Kind,
			&i.CommitmentID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LaunchTier,
			&i.LaunchDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listItemsByProduct = `-- name: ListItemsByProduct :many
SELECT id, product_id, feature_id, title, bucket, start_date, end_date, release_id, audience, status, kind, commitment_id, created_at, updated_at, launch_tier, launch_date FROM roadmap.items WHERE product_id = $1 ORDER BY created_at, id
`

func (q *Queries) ListItemsByProduct(ctx context.Context, productID uuid.UUID) ([]RoadmapItem, error) {
	rows, err := q.db.Query(ctx, listItemsByProduct, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RoadmapItem
	for rows.Next() {
		var i RoadmapItem
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.FeatureID,
			&i.Title,
			&i.Bucket,
			&i.StartDate,
			&i.EndDate,
			&i.ReleaseID,
			&i.Audience,
			&i.Status,
			&i.Kind,
			&i.CommitmentID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LaunchTier,
			&i.LaunchDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReleasesByProduct = `-- name: ListReleasesByProduct :many
SELECT id, product_id, name, version, planned_date, status, branch, base_release_id, feature_ids, release_notes, eol, created_at, updated_at FROM roadmap.releases WHERE product_id = $1 ORDER BY created_at, id
`

func (q *Queries) ListReleasesByProduct(ctx context.Context, productID uuid.UUID) ([]RoadmapRelease, error) {
	rows, err := q.db.Query(ctx, listReleasesByProduct, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RoadmapRelease
	for rows.Next() {
		var i RoadmapRelease
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.Name,
			&i.Version,
			&i.PlannedDate,
			&i.Status,
			&i.Branch,
			&i.BaseReleaseID,
			&i.FeatureIds,
			&i.ReleaseNotes,
			&i.Eol,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markEventProcessed = `-- name: MarkEventProcessed :exec
INSERT INTO roadmap.processed_events (event_id) VALUES ($1) ON CONFLICT (event_id) DO NOTHING
`

func (q *Queries) MarkEventProcessed(ctx context.Context, eventID uuid.UUID) error {
	_, err := q.db.Exec(ctx, markEventProcessed, eventID)
	return err
}

const upsertItem = `-- name: UpsertItem :exec
INSERT INTO roadmap.items (id, product_id, feature_id, title, bucket, start_date, end_date, release_id, audience, status, kind, commitment_id, created_at, updated_at, launch_tier, launch_date)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16)
ON CONFLICT (id) DO UPDATE SET product_id = EXCLUDED.product_id, feature_id = EXCLUDED.feature_id, title = EXCLUDED.title,
  bucket = EXCLUDED.bucket, start_date = EXCLUDED.start_date, end_date = EXCLUDED.end_date, release_id = EXCLUDED.release_id,
  audience = EXCLUDED.audience, status = EXCLUDED.status, kind = EXCLUDED.kind, commitment_id = EXCLUDED.commitment_id,
  updated_at = EXCLUDED.updated_at, launch_tier = EXCLUDED.launch_tier, launch_date = EXCLUDED.launch_date
`

type UpsertItemParams struct {
	ID           uuid.UUID
	ProductID    uuid.UUID
	FeatureID    uuid.NullUUID
	Title        string
	Bucket       string
	StartDate    pgtype.Date
	EndDate      pgtype.Date
	ReleaseID    uuid.NullUUID
	Audience     string
	Status       string
	Kind         string
	CommitmentID uuid.NullUUID
	CreatedAt    time.Time
	UpdatedAt    time.Time
	LaunchTier   string
	LaunchDate   pgtype.Date
}

func (q *Queries) UpsertItem(ctx context.Context, arg UpsertItemParams) error {
	_, err := q.db.Exec(ctx, upsertItem,
		arg.ID,
		arg.ProductID,
		arg.FeatureID,
		arg.Title,
		arg.Bucket,
		arg.StartDate,
		arg.EndDate,
		arg.ReleaseID,
		arg.Audience,
		arg.Status,
		arg.Kind,
		arg.CommitmentID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.LaunchTier,
		arg.LaunchDate,
	)
	return err
}

const upsertRelease = `-- name: UpsertRelease :exec
INSERT INTO roadmap.releases (id, product_id, name, version, planned_date, status, branch, base_release_id, feature_ids, release_notes, eol, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
ON CONFLICT (id) DO UPDATE SET product_id = EXCLUDED.product_id, name = EXCLUDED.name, version = EXCLUDED.version,
  planned_date = EXCLUDED.planned_date, status = EXCLUDED.status, branch = EXCLUDED.branch, base_release_id = EXCLUDED.base_release_id,
  feature_ids = EXCLUDED.feature_ids, release_notes = EXCLUDED.release_notes, eol = EXCLUDED.eol, updated_at = EXCLUDED.updated_at
`

type UpsertReleaseParams struct {
	ID            uuid.UUID
	ProductID     uuid.UUID
	Name          string
	Version       string
	PlannedDate   pgtype.Date
	Status        string
	Branch        string
	BaseReleaseID uuid.NullUUID
	FeatureIds    []uuid.UUID
	ReleaseNotes  string
	Eol           pgtype.Date
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

func (q *Queries) UpsertRelease(ctx context.Context, arg UpsertReleaseParams) error {
	_, err := q.db.Exec(ctx, upsertRelease,
		arg.ID,
		arg.ProductID,
		arg.Name,
		arg.Version,
		arg.PlannedDate,
		arg.Status,
		arg.Branch,
		arg.BaseReleaseID,
		arg.FeatureIds,
		arg.ReleaseNotes,
		arg.Eol,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
