// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"

	"github.com/google/uuid"
)

type PrioritizationDevCost struct {
	FeatureID uuid.UUID
	ProductID uuid.UUID
	Amount    int64
	Currency  string
}

type PrioritizationFeatureFlag struct {
	FeatureID           uuid.UUID
	ProductID           uuid.UUID
	RegulatoryMandatory bool
	Reason              string
	SetBy               string
	SetAt               time.Time
}

type PrioritizationFeatureInput struct {
	ModelID   uuid.UUID
	FeatureID uuid.UUID
	ProductID uuid.UUID
	Values    []byte
	UpdatedAt time.Time
	UpdatedBy string
}

type PrioritizationModel struct {
	ID        uuid.UUID
	ProductID uuid.NullUUID
	Name      string
	Type      string
	Formula   string
	Inputs    []string
	CreatedAt time.Time
	UpdatedAt time.Time
}
