// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: prioritization.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getDevCost = `-- name: GetDevCost :one
SELECT feature_id, product_id, amount, currency FROM prioritization.dev_costs WHERE feature_id = $1
`

func (q *Queries) GetDevCost(ctx context.Context, featureID uuid.UUID) (PrioritizationDevCost, error) {
	row := q.db.QueryRow(ctx, getDevCost, featureID)
	var i PrioritizationDevCost
	err := row.Scan(
		&i.FeatureID,
		&i.ProductID,
		&i.Amount,
		&i.Currency,
	)
	return i, err
}

const getFlags = `-- name: GetFlags :one
SELECT feature_id, product_id, regulatory_mandatory, reason, set_by, set_at FROM prioritization.feature_flags WHERE feature_id = $1
`

func (q *Queries) GetFlags(ctx context.Context, featureID uuid.UUID) (PrioritizationFeatureFlag, error) {
	row := q.db.QueryRow(ctx, getFlags, featureID)
	var i PrioritizationFeatureFlag
	err := row.Scan(
		&i.FeatureID,
		&i.ProductID,
		&i.RegulatoryMandatory,
		&i.Reason,
		&i.SetBy,
		&i.SetAt,
	)
	return i, err
}

const getInputs = `-- name: GetInputs :one
SELECT model_id, feature_id, product_id, values, updated_at, updated_by FROM prioritization.feature_inputs WHERE model_id = $1 AND feature_id = $2
`

type GetInputsParams struct {
	ModelID   uuid.UUID
	FeatureID uuid.UUID
}

func (q *Queries) GetInputs(ctx context.Context, arg GetInputsParams) (PrioritizationFeatureInput, error) {
	row := q.db.QueryRow(ctx, getInputs, arg.ModelID, arg.FeatureID)
	var i PrioritizationFeatureInput
	err := row.Scan(
		&i.ModelID,
		&i.FeatureID,
		&i.ProductID,
		&i.Values,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const getModel = `-- name: GetModel :one
SELECT id, product_id, name, type, formula, inputs, created_at, updated_at FROM prioritization.models WHERE id = $1
`

func (q *Queries) GetModel(ctx context.Context, id uuid.UUID) (PrioritizationModel, error) {
	row := q.db.QueryRow(ctx, getModel, id)
	var i PrioritizationModel
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Name,
		&i.Type,
		&i.Formula,
		&i.Inputs,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listInputsByProduct = `-- name: ListInputsByProduct :many
SELECT model_id, feature_id, product_id, values, updated_at, updated_by FROM prioritization.feature_inputs WHERE model_id = $1 AND product_id = $2 ORDER BY feature_id
`

type ListInputsByProductParams struct {
	ModelID   uuid.UUID
	ProductID uuid.UUID
}

func (q *Queries) ListInputsByProduct(ctx context.Context, arg ListInputsByProductParams) ([]PrioritizationFeatureInput, error) {
	rows, err := q.db.Query(ctx, listInputsByProduct, arg.ModelID, arg.ProductID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PrioritizationFeatureInput
	for rows.Next() {
		var i PrioritizationFeatureInput
		if err := rows.Scan(
			&i.ModelID,
			&i.FeatureID,
			&i.ProductID,
			&i.Values,
			&i.UpdatedAt,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listModels = `-- name: ListModels :many
SELECT id, product_id, name, type, formula, inputs, created_at, updated_at FROM prioritization.models ORDER BY created_at, id
`

func (q *Queries) ListModels(ctx context.Context) ([]PrioritizationModel, error) {
	rows, err := q.db.Query(ctx, listModels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PrioritizationModel
	for rows.Next() {
		var i PrioritizationModel
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.Name,
			&i.Type,
			&i.Formula,
			&i.Inputs,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertDevCost = `-- name: UpsertDevCost :exec
INSERT INTO prioritization.dev_costs (feature_id, product_id, amount, currency) VALUES ($1, $2, $3, $4)
ON CONFLICT (feature_id) DO UPDATE SET product_id = EXCLUDED.product_id, amount = EXCLUDED.amount, currency = EXCLUDED.currency
`

type UpsertDevCostParams struct {
	FeatureID uuid.UUID
	ProductID uuid.UUID
	Amount    int64
	Currency  string
}

func (q *Queries) UpsertDevCost(ctx context.Context, arg UpsertDevCostParams) error {
	_, err := q.db.Exec(ctx, upsertDevCost,
		arg.FeatureID,
		arg.ProductID,
		arg.Amount,
		arg.Currency,
	)
	return err
}

const upsertFlags = `-- name: UpsertFlags :exec
INSERT INTO prioritization.feature_flags (feature_id, product_id, regulatory_mandatory, reason, set_by, set_at)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (feature_id) DO UPDATE SET product_id = EXCLUDED.product_id, regulatory_mandatory = EXCLUDED.regulatory_mandatory,
  reason = EXCLUDED.reason, set_by = EXCLUDED.set_by, set_at = EXCLUDED.set_at
`

type UpsertFlagsParams struct {
	FeatureID           uuid.UUID
	ProductID           uuid.UUID
	RegulatoryMandatory bool
	Reason              string
	SetBy               string
	SetAt               time.Time
}

func (q *Queries) UpsertFlags(ctx context.Context, arg UpsertFlagsParams) error {
	_, err := q.db.Exec(ctx, upsertFlags,
		arg.FeatureID,
		arg.ProductID,
		arg.RegulatoryMandatory,
		arg.Reason,
		arg.SetBy,
		arg.SetAt,
	)
	return err
}

const upsertInputs = `-- name: UpsertInputs :exec
INSERT INTO prioritization.feature_inputs (model_id, feature_id, product_id, values, updated_at, updated_by)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (model_id, feature_id) DO UPDATE SET product_id = EXCLUDED.product_id, values = EXCLUDED.values,
  updated_at = EXCLUDED.updated_at, updated_by = EXCLUDED.updated_by
`

type UpsertInputsParams struct {
	ModelID   uuid.UUID
	FeatureID uuid.UUID
	ProductID uuid.UUID
	Values    []byte
	UpdatedAt time.Time
	UpdatedBy string
}

func (q *Queries) UpsertInputs(ctx context.Context, arg UpsertInputsParams) error {
	_, err := q.db.Exec(ctx, upsertInputs,
		arg.ModelID,
		arg.FeatureID,
		arg.ProductID,
		arg.Values,
		arg.UpdatedAt,
		arg.UpdatedBy,
	)
	return err
}

const upsertModel = `-- name: UpsertModel :exec
INSERT INTO prioritization.models (id, product_id, name, type, formula, inputs, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (id) DO UPDATE SET product_id = EXCLUDED.product_id, name = EXCLUDED.name, type = EXCLUDED.type,
  formula = EXCLUDED.formula, inputs = EXCLUDED.inputs, updated_at = EXCLUDED.updated_at
`

type UpsertModelParams struct {
	ID        uuid.UUID
	ProductID uuid.NullUUID
	Name      string
	Type      string
	Formula   string
	Inputs    []string
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) UpsertModel(ctx context.Context, arg UpsertModelParams) error {
	_, err := q.db.Exec(ctx, upsertModel,
		arg.ID,
		arg.ProductID,
		arg.Name,
		arg.Type,
		arg.Formula,
		arg.Inputs,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
