// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: discovery.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const deleteEmbedding = `-- name: DeleteEmbedding :exec
DELETE FROM discovery.embeddings WHERE kind = $1 AND id = $2
`

type DeleteEmbeddingParams struct {
	Kind string
	ID   uuid.UUID
}

func (q *Queries) DeleteEmbedding(ctx context.Context, arg DeleteEmbeddingParams) error {
	_, err := q.db.Exec(ctx, deleteEmbedding, arg.Kind, arg.ID)
	return err
}

const getEvidence = `-- name: GetEvidence :one
SELECT id, product_id, source, source_ref, date, trust, verification, sha256, hypothesis_id, insight_id, feature_id, created_by, created_at, updated_at FROM discovery.evidence WHERE id = $1
`

func (q *Queries) GetEvidence(ctx context.Context, id uuid.UUID) (DiscoveryEvidence, error) {
	row := q.db.QueryRow(ctx, getEvidence, id)
	var i DiscoveryEvidence
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Source,
		&i.SourceRef,
		&i.Date,
		&i.Trust,
		&i.Verification,
		&i.Sha256,
		&i.HypothesisID,
		&i.InsightID,
		&i.FeatureID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getHypothesis = `-- name: GetHypothesis :one
SELECT id, product_id, title, statement, assumptions, confirmation_criterion, status, resolution, feature_id, custom_fields, created_by, created_at, updated_at FROM discovery.hypotheses WHERE id = $1
`

func (q *Queries) GetHypothesis(ctx context.Context, id uuid.UUID) (DiscoveryHypothesis, error) {
	row := q.db.QueryRow(ctx, getHypothesis, id)
	var i DiscoveryHypothesis
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Title,
		&i.Statement,
		&i.Assumptions,
		&i.ConfirmationCriterion,
		&i.Status,
		&i.Resolution,
		&i.FeatureID,
		&i.CustomFields,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getInsight = `-- name: GetInsight :one
SELECT id, product_id, text, interview_id, hypothesis_ids, signal_ids, confidence, created_by, created_at, updated_at FROM discovery.insights WHERE id = $1
`

func (q *Queries) GetInsight(ctx context.Context, id uuid.UUID) (DiscoveryInsight, error) {
	row := q.db.QueryRow(ctx, getInsight, id)
	var i DiscoveryInsight
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Text,
		&i.InterviewID,
		&i.HypothesisIds,
		&i.SignalIds,
		&i.Confidence,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getInterview = `-- name: GetInterview :one
SELECT id, product_id, account_id, segment, date, participants, notes, hypothesis_ids, created_by, created_at, updated_at FROM discovery.interviews WHERE id = $1
`

func (q *Queries) GetInterview(ctx context.Context, id uuid.UUID) (DiscoveryInterview, error) {
	row := q.db.QueryRow(ctx, getInterview, id)
	var i DiscoveryInterview
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.AccountID,
		&i.Segment,
		&i.Date,
		&i.Participants,
		&i.Notes,
		&i.HypothesisIds,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const lexemes = `-- name: Lexemes :one
SELECT array_to_string(tsvector_to_array(to_tsvector('russian', $1::text)), ' or ')::text AS lexemes
`

func (q *Queries) Lexemes(ctx context.Context, text string) (string, error) {
	row := q.db.QueryRow(ctx, lexemes, text)
	var lexemes string
	err := row.Scan(&lexemes)
	return lexemes, err
}

const listEvidence = `-- name: ListEvidence :many
SELECT id, product_id, source, source_ref, date, trust, verification, sha256, hypothesis_id, insight_id, feature_id, created_by, created_at, updated_at FROM discovery.evidence
WHERE ($1::uuid IS NULL OR product_id = $1::uuid)
  AND ($2::uuid IS NULL OR hypothesis_id = $2::uuid)
  AND ($3::uuid IS NULL OR insight_id = $3::uuid)
  AND ($4::uuid IS NULL OR feature_id = $4::uuid)
  AND ($5::text = '' OR verification = $5::text)
ORDER BY created_at, id
`

type ListEvidenceParams struct {
	ProductID    uuid.NullUUID
	HypothesisID uuid.NullUUID
	InsightID    uuid.NullUUID
	FeatureID    uuid.NullUUID
	Verification string
}

func (q *Queries) ListEvidence(ctx context.Context, arg ListEvidenceParams) ([]DiscoveryEvidence, error) {
	rows, err := q.db.Query(ctx, listEvidence,
		arg.ProductID,
		arg.HypothesisID,
		arg.InsightID,
		arg.FeatureID,
		arg.Verification,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DiscoveryEvidence
	for rows.Next() {
		var i DiscoveryEvidence
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.Source,
			&i.SourceRef,
			&i.Date,
			&i.Trust,
			&i.Verification,
			&i.Sha256,
			&i.HypothesisID,
			&i.InsightID,
			&i.FeatureID,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFieldDefs = `-- name: ListFieldDefs :many
SELECT seq, id, entity, key, label, type, options, required FROM discovery.field_defs WHERE entity = $1 ORDER BY seq
`

func (q *Queries) ListFieldDefs(ctx context.Context, entity string) ([]DiscoveryFieldDef, error) {
	rows, err := q.db.Query(ctx, listFieldDefs, entity)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DiscoveryFieldDef
	for rows.Next() {
		var i DiscoveryFieldDef
		if err := rows.Scan(
			&i.Seq,
			&i.ID,
			&i.Entity,
			&i.Key,
			&i.Label,
			&i.Type,
			&i.Options,
			&i.Required,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHypotheses = `-- name: ListHypotheses :many
SELECT id, product_id, title, statement, assumptions, confirmation_criterion, status, resolution, feature_id, custom_fields, created_by, created_at, updated_at FROM discovery.hypotheses
WHERE ($1::uuid IS NULL OR product_id = $1::uuid)
  AND ($2::uuid IS NULL OR feature_id = $2::uuid)
  AND (cardinality($3::text[]) = 0 OR status = ANY($3::text[]))
ORDER BY created_at, id
`

type ListHypothesesParams struct {
	ProductID uuid.NullUUID
	FeatureID uuid.NullUUID
	Statuses  []string
}

func (q *Queries) ListHypotheses(ctx context.Context, arg ListHypothesesParams) ([]DiscoveryHypothesis, error) {
	rows, err := q.db.Query(ctx, listHypotheses, arg.ProductID, arg.FeatureID, arg.Statuses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DiscoveryHypothesis
	for rows.Next() {
		var i DiscoveryHypothesis
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.Title,
			&i.Statement,
			&i.Assumptions,
			&i.ConfirmationCriterion,
			&i.Status,
			&i.Resolution,
			&i.FeatureID,
			&i.CustomFields,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInsights = `-- name: ListInsights :many
SELECT id, product_id, text, interview_id, hypothesis_ids, signal_ids, confidence, created_by, created_at, updated_at FROM discovery.insights
WHERE ($1::uuid IS NULL OR product_id = $1::uuid)
  AND ($2::uuid IS NULL OR interview_id = $2::uuid)
  AND ($3::uuid IS NULL OR $3::uuid = ANY(hypothesis_ids))
  AND ($4::uuid IS NULL OR $4::uuid = ANY(signal_ids))
ORDER BY created_at, id
`

type ListInsightsParams struct {
	ProductID    uuid.NullUUID
	InterviewID  uuid.NullUUID
	HypothesisID uuid.NullUUID
	SignalID     uuid.NullUUID
}

func (q *Queries) ListInsights(ctx context.Context, arg ListInsightsParams) ([]DiscoveryInsight, error) {
	rows, err := q.db.Query(ctx, listInsights,
		arg.ProductID,
		arg.InterviewID,
		arg.HypothesisID,
		arg.SignalID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DiscoveryInsight
	for rows.Next() {
		var i DiscoveryInsight
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.Text,
			&i.InterviewID,
			&i.HypothesisIds,
			&i.SignalIds,
			&i.Confidence,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInterviews = `-- name: ListInterviews :many
SELECT id, product_id, account_id, segment, date, participants, notes, hypothesis_ids, created_by, created_at, updated_at FROM discovery.interviews
WHERE ($1::uuid IS NULL OR product_id = $1::uuid)
ORDER BY created_at, id
`

func (q *Queries) ListInterviews(ctx context.Context, productID uuid.NullUUID) ([]DiscoveryInterview, error) {
	rows, err := q.db.Query(ctx, listInterviews, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DiscoveryInterview
	for rows.Next() {
		var i DiscoveryInterview
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.AccountID,
			&i.Segment,
			&i.Date,
			&i.Participants,
			&i.Notes,
			&i.HypothesisIds,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStatusDefs = `-- name: ListStatusDefs :many
SELECT seq, entity, key, label, category FROM discovery.status_defs WHERE entity = $1 ORDER BY seq
`

func (q *Queries) ListStatusDefs(ctx context.Context, entity string) ([]DiscoveryStatusDef, error) {
	rows, err := q.db.Query(ctx, listStatusDefs, entity)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DiscoveryStatusDef
	for rows.Next() {
		var i DiscoveryStatusDef
		if err := rows.Scan(
			&i.Seq,
			&i.Entity,
			&i.Key,
			&i.Label,
			&i.Category,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const similarEmbeddings = `-- name: SimilarEmbeddings :many
SELECT e.id, ts_rank_cd(e.tsv, q.query, 1 | 32)::float8 AS score
FROM discovery.embeddings e, websearch_to_tsquery('simple', $1::text) q(query)
WHERE e.kind = $2 AND e.product_id = $3 AND e.tsv @@ q.query
ORDER BY score DESC, e.id
LIMIT $4::bigint
`

type SimilarEmbeddingsParams struct {
	Lexemes   string
	Kind      string
	ProductID uuid.UUID
	Lim       int64
}

type SimilarEmbeddingsRow struct {
	ID    uuid.UUID
	Score float64
}

func (q *Queries) SimilarEmbeddings(ctx context.Context, arg SimilarEmbeddingsParams) ([]SimilarEmbeddingsRow, error) {
	rows, err := q.db.Query(ctx, similarEmbeddings,
		arg.Lexemes,
		arg.Kind,
		arg.ProductID,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SimilarEmbeddingsRow
	for rows.Next() {
		var i SimilarEmbeddingsRow
		if err := rows.Scan(&i.ID, &i.Score); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertEmbedding = `-- name: UpsertEmbedding :exec
INSERT INTO discovery.embeddings (kind, id, product_id, text) VALUES ($1, $2, $3, $4)
ON CONFLICT (kind, id) DO UPDATE SET product_id = EXCLUDED.product_id, text = EXCLUDED.text
`

type UpsertEmbeddingParams struct {
	Kind      string
	ID        uuid.UUID
	ProductID uuid.UUID
	Text      string
}

func (q *Queries) UpsertEmbedding(ctx context.Context, arg UpsertEmbeddingParams) error {
	_, err := q.db.Exec(ctx, upsertEmbedding,
		arg.Kind,
		arg.ID,
		arg.ProductID,
		arg.Text,
	)
	return err
}

const upsertEvidence = `-- name: UpsertEvidence :exec
INSERT INTO discovery.evidence (id, product_id, source, source_ref, date, trust, verification, sha256, hypothesis_id, insight_id, feature_id, created_by, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
ON CONFLICT (id) DO UPDATE SET product_id = EXCLUDED.product_id, source = EXCLUDED.source, source_ref = EXCLUDED.source_ref,
  date = EXCLUDED.date, trust = EXCLUDED.trust, verification = EXCLUDED.verification, sha256 = EXCLUDED.sha256,
  hypothesis_id = EXCLUDED.hypothesis_id, insight_id = EXCLUDED.insight_id, feature_id = EXCLUDED.feature_id,
  created_by = EXCLUDED.created_by, updated_at = EXCLUDED.updated_at
`

type UpsertEvidenceParams struct {
	ID           uuid.UUID
	ProductID    uuid.UUID
	Source       string
	SourceRef    string
	Date         pgtype.Date
	Trust        string
	Verification string
	Sha256       string
	HypothesisID uuid.NullUUID
	InsightID    uuid.NullUUID
	FeatureID    uuid.NullUUID
	CreatedBy    string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

func (q *Queries) UpsertEvidence(ctx context.Context, arg UpsertEvidenceParams) error {
	_, err := q.db.Exec(ctx, upsertEvidence,
		arg.ID,
		arg.ProductID,
		arg.Source,
		arg.SourceRef,
		arg.Date,
		arg.Trust,
		arg.Verification,
		arg.Sha256,
		arg.HypothesisID,
		arg.InsightID,
		arg.FeatureID,
		arg.CreatedBy,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const upsertFieldDef = `-- name: UpsertFieldDef :exec
INSERT INTO discovery.field_defs (id, entity, key, label, type, options, required) VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (entity, key) DO UPDATE SET id = EXCLUDED.id, label = EXCLUDED.label, type = EXCLUDED.type,
  options = EXCLUDED.options, required = EXCLUDED.required
`

type UpsertFieldDefParams struct {
	ID       uuid.UUID
	Entity   string
	Key      string
	Label    string
	Type     string
	Options  []string
	Required bool
}

func (q *Queries) UpsertFieldDef(ctx context.Context, arg UpsertFieldDefParams) error {
	_, err := q.db.Exec(ctx, upsertFieldDef,
		arg.ID,
		arg.Entity,
		arg.Key,
		arg.Label,
		arg.Type,
		arg.Options,
		arg.Required,
	)
	return err
}

const upsertHypothesis = `-- name: UpsertHypothesis :exec
INSERT INTO discovery.hypotheses (id, product_id, title, statement, assumptions, confirmation_criterion, status, resolution, feature_id, custom_fields, created_by, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
ON CONFLICT (id) DO UPDATE SET product_id = EXCLUDED.product_id, title = EXCLUDED.title, statement = EXCLUDED.statement,
  assumptions = EXCLUDED.assumptions, confirmation_criterion = EXCLUDED.confirmation_criterion, status = EXCLUDED.status,
  resolution = EXCLUDED.resolution, feature_id = EXCLUDED.feature_id, custom_fields = EXCLUDED.custom_fields,
  created_by = EXCLUDED.created_by, updated_at = EXCLUDED.updated_at
`

type UpsertHypothesisParams struct {
	ID                    uuid.UUID
	ProductID             uuid.UUID
	Title                 string
	Statement             string
	Assumptions           []string
	ConfirmationCriterion string
	Status                string
	Resolution            string
	FeatureID             uuid.NullUUID
	CustomFields          []byte
	CreatedBy             string
	CreatedAt             time.Time
	UpdatedAt             time.Time
}

func (q *Queries) UpsertHypothesis(ctx context.Context, arg UpsertHypothesisParams) error {
	_, err := q.db.Exec(ctx, upsertHypothesis,
		arg.ID,
		arg.ProductID,
		arg.Title,
		arg.Statement,
		arg.Assumptions,
		arg.ConfirmationCriterion,
		arg.Status,
		arg.Resolution,
		arg.FeatureID,
		arg.CustomFields,
		arg.CreatedBy,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const upsertInsight = `-- name: UpsertInsight :exec
INSERT INTO discovery.insights (id, product_id, text, interview_id, hypothesis_ids, signal_ids, confidence, created_by, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
ON CONFLICT (id) DO UPDATE SET product_id = EXCLUDED.product_id, text = EXCLUDED.text, interview_id = EXCLUDED.interview_id,
  hypothesis_ids = EXCLUDED.hypothesis_ids, signal_ids = EXCLUDED.signal_ids, confidence = EXCLUDED.confidence,
  created_by = EXCLUDED.created_by, updated_at = EXCLUDED.updated_at
`

type UpsertInsightParams struct {
	ID            uuid.UUID
	ProductID     uuid.UUID
	Text          string
	InterviewID   uuid.NullUUID
	HypothesisIds []uuid.UUID
	SignalIds     []uuid.UUID
	Confidence    string
	CreatedBy     string
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

func (q *Queries) UpsertInsight(ctx context.Context, arg UpsertInsightParams) error {
	_, err := q.db.Exec(ctx, upsertInsight,
		arg.ID,
		arg.ProductID,
		arg.Text,
		arg.InterviewID,
		arg.HypothesisIds,
		arg.SignalIds,
		arg.Confidence,
		arg.CreatedBy,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const upsertInterview = `-- name: UpsertInterview :exec
INSERT INTO discovery.interviews (id, product_id, account_id, segment, date, participants, notes, hypothesis_ids, created_by, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
ON CONFLICT (id) DO UPDATE SET product_id = EXCLUDED.product_id, account_id = EXCLUDED.account_id, segment = EXCLUDED.segment,
  date = EXCLUDED.date, participants = EXCLUDED.participants, notes = EXCLUDED.notes, hypothesis_ids = EXCLUDED.hypothesis_ids,
  created_by = EXCLUDED.created_by, updated_at = EXCLUDED.updated_at
`

type UpsertInterviewParams struct {
	ID            uuid.UUID
	ProductID     uuid.UUID
	AccountID     string
	Segment       string
	Date          pgtype.Date
	Participants  []string
	Notes         string
	HypothesisIds []uuid.UUID
	CreatedBy     string
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

func (q *Queries) UpsertInterview(ctx context.Context, arg UpsertInterviewParams) error {
	_, err := q.db.Exec(ctx, upsertInterview,
		arg.ID,
		arg.ProductID,
		arg.AccountID,
		arg.Segment,
		arg.Date,
		arg.Participants,
		arg.Notes,
		arg.HypothesisIds,
		arg.CreatedBy,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const upsertStatusDef = `-- name: UpsertStatusDef :exec
INSERT INTO discovery.status_defs (entity, key, label, category) VALUES ($1, $2, $3, $4)
ON CONFLICT (entity, key) DO UPDATE SET label = EXCLUDED.label, category = EXCLUDED.category
`

type UpsertStatusDefParams struct {
	Entity   string
	Key      string
	Label    string
	Category string
}

func (q *Queries) UpsertStatusDef(ctx context.Context, arg UpsertStatusDefParams) error {
	_, err := q.db.Exec(ctx, upsertStatusDef,
		arg.Entity,
		arg.Key,
		arg.Label,
		arg.Category,
	)
	return err
}
