// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type DiscoveryEmbedding struct {
	Kind      string
	ID        uuid.UUID
	ProductID uuid.UUID
	Text      string
	Tsv       interface{}
}

type DiscoveryEvidence struct {
	ID           uuid.UUID
	ProductID    uuid.UUID
	Source       string
	SourceRef    string
	Date         pgtype.Date
	Trust        string
	Verification string
	Sha256       string
	HypothesisID uuid.NullUUID
	InsightID    uuid.NullUUID
	FeatureID    uuid.NullUUID
	CreatedBy    string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type DiscoveryFieldDef struct {
	Seq      pgtype.Int8
	ID       uuid.UUID
	Entity   string
	Key      string
	Label    string
	Type     string
	Options  []string
	Required bool
}

type DiscoveryHypothesis struct {
	ID                    uuid.UUID
	ProductID             uuid.UUID
	Title                 string
	Statement             string
	Assumptions           []string
	ConfirmationCriterion string
	Status                string
	Resolution            string
	FeatureID             uuid.NullUUID
	CustomFields          []byte
	CreatedBy             string
	CreatedAt             time.Time
	UpdatedAt             time.Time
}

type DiscoveryInsight struct {
	ID            uuid.UUID
	ProductID     uuid.UUID
	Text          string
	InterviewID   uuid.NullUUID
	HypothesisIds []uuid.UUID
	SignalIds     []uuid.UUID
	Confidence    string
	CreatedBy     string
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type DiscoveryInterview struct {
	ID            uuid.UUID
	ProductID     uuid.UUID
	AccountID     string
	Segment       string
	Date          pgtype.Date
	Participants  []string
	Notes         string
	HypothesisIds []uuid.UUID
	CreatedBy     string
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type DiscoveryStatusDef struct {
	Seq      pgtype.Int8
	Entity   string
	Key      string
	Label    string
	Category string
}
