// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type KernelOutbox struct {
	ID            uuid.UUID
	EventType     string
	AggregateID   uuid.UUID
	ProductID     uuid.NullUUID
	OccurredAt    time.Time
	Actor         string
	Payload       []byte
	Attempts      int32
	NextAttemptAt time.Time
	LastError     pgtype.Text
	CreatedAt     time.Time
}

type KernelOutboxDlq struct {
	ID          uuid.UUID
	EventType   string
	AggregateID uuid.UUID
	ProductID   uuid.NullUUID
	OccurredAt  time.Time
	Actor       string
	Payload     []byte
	Attempts    int32
	Error       string
	CreatedAt   time.Time
	FailedAt    time.Time
}
