// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: outbox.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const claimOutbox = `-- name: ClaimOutbox :many
SELECT id, event_type, aggregate_id, product_id, occurred_at, actor, payload, attempts, next_attempt_at, last_error, created_at
FROM kernel.outbox
WHERE next_attempt_at <= $1
ORDER BY next_attempt_at, created_at
LIMIT $2
FOR UPDATE SKIP LOCKED
`

type ClaimOutboxParams struct {
	NextAttemptAt time.Time
	Limit         int32
}

func (q *Queries) ClaimOutbox(ctx context.Context, arg ClaimOutboxParams) ([]KernelOutbox, error) {
	rows, err := q.db.Query(ctx, claimOutbox, arg.NextAttemptAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []KernelOutbox
	for rows.Next() {
		var i KernelOutbox
		if err := rows.Scan(
			&i.ID,
			&i.EventType,
			&i.AggregateID,
			&i.ProductID,
			&i.OccurredAt,
			&i.Actor,
			&i.Payload,
			&i.Attempts,
			&i.NextAttemptAt,
			&i.LastError,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countDLQ = `-- name: CountDLQ :one
SELECT count(*) FROM kernel.outbox_dlq
`

func (q *Queries) CountDLQ(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countDLQ)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteDLQ = `-- name: DeleteDLQ :exec
DELETE FROM kernel.outbox_dlq WHERE id = $1
`

func (q *Queries) DeleteDLQ(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteDLQ, id)
	return err
}

const deleteOutbox = `-- name: DeleteOutbox :exec
DELETE FROM kernel.outbox WHERE id = $1
`

func (q *Queries) DeleteOutbox(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteOutbox, id)
	return err
}

const insertOutbox = `-- name: InsertOutbox :exec
INSERT INTO kernel.outbox (id, event_type, aggregate_id, product_id, occurred_at, actor, payload, next_attempt_at, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $8)
`

type InsertOutboxParams struct {
	ID            uuid.UUID
	EventType     string
	AggregateID   uuid.UUID
	ProductID     uuid.NullUUID
	OccurredAt    time.Time
	Actor         string
	Payload       []byte
	NextAttemptAt time.Time
}

func (q *Queries) InsertOutbox(ctx context.Context, arg InsertOutboxParams) error {
	_, err := q.db.Exec(ctx, insertOutbox,
		arg.ID,
		arg.EventType,
		arg.AggregateID,
		arg.ProductID,
		arg.OccurredAt,
		arg.Actor,
		arg.Payload,
		arg.NextAttemptAt,
	)
	return err
}

const listDLQ = `-- name: ListDLQ :many
SELECT id, event_type, aggregate_id, product_id, occurred_at, actor, payload, attempts, error, created_at, failed_at
FROM kernel.outbox_dlq
ORDER BY failed_at DESC
LIMIT $1
`

func (q *Queries) ListDLQ(ctx context.Context, limit int32) ([]KernelOutboxDlq, error) {
	rows, err := q.db.Query(ctx, listDLQ, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []KernelOutboxDlq
	for rows.Next() {
		var i KernelOutboxDlq
		if err := rows.Scan(
			&i.ID,
			&i.EventType,
			&i.AggregateID,
			&i.ProductID,
			&i.OccurredAt,
			&i.Actor,
			&i.Payload,
			&i.Attempts,
			&i.Error,
			&i.CreatedAt,
			&i.FailedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const moveOutboxToDLQ = `-- name: MoveOutboxToDLQ :exec
INSERT INTO kernel.outbox_dlq (id, event_type, aggregate_id, product_id, occurred_at, actor, payload, attempts, error, created_at, failed_at)
SELECT o.id, o.event_type, o.aggregate_id, o.product_id, o.occurred_at, o.actor, o.payload, $2, $3, o.created_at, $4
FROM kernel.outbox o WHERE o.id = $1
`

type MoveOutboxToDLQParams struct {
	ID       uuid.UUID
	Attempts int32
	Error    string
	FailedAt time.Time
}

func (q *Queries) MoveOutboxToDLQ(ctx context.Context, arg MoveOutboxToDLQParams) error {
	_, err := q.db.Exec(ctx, moveOutboxToDLQ,
		arg.ID,
		arg.Attempts,
		arg.Error,
		arg.FailedAt,
	)
	return err
}

const requeueFromDLQ = `-- name: RequeueFromDLQ :execrows
INSERT INTO kernel.outbox (id, event_type, aggregate_id, product_id, occurred_at, actor, payload, attempts, next_attempt_at, last_error, created_at)
SELECT d.id, d.event_type, d.aggregate_id, d.product_id, d.occurred_at, d.actor, d.payload, 0, $2, d.error, d.created_at
FROM kernel.outbox_dlq d WHERE d.id = $1
`

type RequeueFromDLQParams struct {
	ID            uuid.UUID
	NextAttemptAt time.Time
}

func (q *Queries) RequeueFromDLQ(ctx context.Context, arg RequeueFromDLQParams) (int64, error) {
	result, err := q.db.Exec(ctx, requeueFromDLQ, arg.ID, arg.NextAttemptAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const retryOutbox = `-- name: RetryOutbox :exec
UPDATE kernel.outbox
SET attempts = $2, next_attempt_at = $3, last_error = $4
WHERE id = $1
`

type RetryOutboxParams struct {
	ID            uuid.UUID
	Attempts      int32
	NextAttemptAt time.Time
	LastError     pgtype.Text
}

func (q *Queries) RetryOutbox(ctx context.Context, arg RetryOutboxParams) error {
	_, err := q.db.Exec(ctx, retryOutbox,
		arg.ID,
		arg.Attempts,
		arg.NextAttemptAt,
		arg.LastError,
	)
	return err
}
