// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: compliance.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const evidenceAfter = `-- name: EvidenceAfter :many
SELECT seq, id, product_id, track_id, gate_id, url, sha256, status, comment, supersedes, actor, at, prev_hash, hash FROM compliance.evidence_log WHERE seq > $1 ORDER BY seq LIMIT $2::bigint
`

type EvidenceAfterParams struct {
	Seq int64
	Lim int64
}

func (q *Queries) EvidenceAfter(ctx context.Context, arg EvidenceAfterParams) ([]ComplianceEvidenceLog, error) {
	rows, err := q.db.Query(ctx, evidenceAfter, arg.Seq, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ComplianceEvidenceLog
	for rows.Next() {
		var i ComplianceEvidenceLog
		if err := rows.Scan(
			&i.Seq,
			&i.ID,
			&i.ProductID,
			&i.TrackID,
			&i.GateID,
			&i.Url,
			&i.Sha256,
			&i.Status,
			&i.Comment,
			&i.Supersedes,
			&i.Actor,
			&i.At,
			&i.PrevHash,
			&i.Hash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBaseline = `-- name: GetBaseline :one
SELECT id, product_id, track_id, version, requirement_set_id, certificate_no, certified_at, eol, created_at FROM compliance.baselines WHERE id = $1
`

func (q *Queries) GetBaseline(ctx context.Context, id uuid.UUID) (ComplianceBaseline, error) {
	row := q.db.QueryRow(ctx, getBaseline, id)
	var i ComplianceBaseline
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.TrackID,
		&i.Version,
		&i.RequirementSetID,
		&i.CertificateNo,
		&i.CertifiedAt,
		&i.Eol,
		&i.CreatedAt,
	)
	return i, err
}

const getRequirementSet = `-- name: GetRequirementSet :one
SELECT id, code, version, product_type, items, status, created_by, created_at, updated_at FROM compliance.requirement_sets WHERE id = $1
`

func (q *Queries) GetRequirementSet(ctx context.Context, id uuid.UUID) (ComplianceRequirementSet, error) {
	row := q.db.QueryRow(ctx, getRequirementSet, id)
	var i ComplianceRequirementSet
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Version,
		&i.ProductType,
		&i.Items,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSettings = `-- name: GetSettings :one
SELECT value FROM compliance.settings WHERE singleton = true
`

func (q *Queries) GetSettings(ctx context.Context) ([]byte, error) {
	row := q.db.QueryRow(ctx, getSettings)
	var value []byte
	err := row.Scan(&value)
	return value, err
}

const getTemplate = `-- name: GetTemplate :one
SELECT id, product_type, name, gates, created_at, updated_at FROM compliance.track_templates WHERE id = $1
`

func (q *Queries) GetTemplate(ctx context.Context, id uuid.UUID) (ComplianceTrackTemplate, error) {
	row := q.db.QueryRow(ctx, getTemplate, id)
	var i ComplianceTrackTemplate
	err := row.Scan(
		&i.ID,
		&i.ProductType,
		&i.Name,
		&i.Gates,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTrack = `-- name: GetTrack :one
SELECT id, product_id, release_id, version, template_id, status, gates, baseline_id, created_by, created_at, updated_at FROM compliance.tracks WHERE id = $1
`

func (q *Queries) GetTrack(ctx context.Context, id uuid.UUID) (ComplianceTrack, error) {
	row := q.db.QueryRow(ctx, getTrack, id)
	var i ComplianceTrack
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.ReleaseID,
		&i.Version,
		&i.TemplateID,
		&i.Status,
		&i.Gates,
		&i.BaselineID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertEvidence = `-- name: InsertEvidence :exec
INSERT INTO compliance.evidence_log (seq, id, product_id, track_id, gate_id, url, sha256, status, comment, supersedes, actor, at, prev_hash, hash)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
`

type InsertEvidenceParams struct {
	Seq        int64
	ID         uuid.UUID
	ProductID  uuid.UUID
	TrackID    uuid.UUID
	GateID     uuid.UUID
	Url        string
	Sha256     string
	Status     string
	Comment    string
	Supersedes int64
	Actor      string
	At         time.Time
	PrevHash   string
	Hash       string
}

func (q *Queries) InsertEvidence(ctx context.Context, arg InsertEvidenceParams) error {
	_, err := q.db.Exec(ctx, insertEvidence,
		arg.Seq,
		arg.ID,
		arg.ProductID,
		arg.TrackID,
		arg.GateID,
		arg.Url,
		arg.Sha256,
		arg.Status,
		arg.Comment,
		arg.Supersedes,
		arg.Actor,
		arg.At,
		arg.PrevHash,
		arg.Hash,
	)
	return err
}

const insertImpact = `-- name: InsertImpact :exec
INSERT INTO compliance.impact_assessments (id, feature_id, product_id, class, justification, author, at) VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertImpactParams struct {
	ID            uuid.UUID
	FeatureID     uuid.UUID
	ProductID     uuid.UUID
	Class         string
	Justification string
	Author        string
	At            time.Time
}

func (q *Queries) InsertImpact(ctx context.Context, arg InsertImpactParams) error {
	_, err := q.db.Exec(ctx, insertImpact,
		arg.ID,
		arg.FeatureID,
		arg.ProductID,
		arg.Class,
		arg.Justification,
		arg.Author,
		arg.At,
	)
	return err
}

const lastEvidence = `-- name: LastEvidence :one
SELECT seq, id, product_id, track_id, gate_id, url, sha256, status, comment, supersedes, actor, at, prev_hash, hash FROM compliance.evidence_log ORDER BY seq DESC LIMIT 1
`

func (q *Queries) LastEvidence(ctx context.Context) (ComplianceEvidenceLog, error) {
	row := q.db.QueryRow(ctx, lastEvidence)
	var i ComplianceEvidenceLog
	err := row.Scan(
		&i.Seq,
		&i.ID,
		&i.ProductID,
		&i.TrackID,
		&i.GateID,
		&i.Url,
		&i.Sha256,
		&i.Status,
		&i.Comment,
		&i.Supersedes,
		&i.Actor,
		&i.At,
		&i.PrevHash,
		&i.Hash,
	)
	return i, err
}

const listBaselines = `-- name: ListBaselines :many
SELECT id, product_id, track_id, version, requirement_set_id, certificate_no, certified_at, eol, created_at FROM compliance.baselines WHERE ($1::uuid IS NULL OR product_id = $1::uuid) ORDER BY created_at, id
`

func (q *Queries) ListBaselines(ctx context.Context, productID uuid.NullUUID) ([]ComplianceBaseline, error) {
	rows, err := q.db.Query(ctx, listBaselines, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ComplianceBaseline
	for rows.Next() {
		var i ComplianceBaseline
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.TrackID,
			&i.Version,
			&i.RequirementSetID,
			&i.CertificateNo,
			&i.CertifiedAt,
			&i.Eol,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listImpactHistory = `-- name: ListImpactHistory :many
SELECT seq, id, feature_id, product_id, class, justification, author, at FROM compliance.impact_assessments WHERE feature_id = $1 ORDER BY seq
`

func (q *Queries) ListImpactHistory(ctx context.Context, featureID uuid.UUID) ([]ComplianceImpactAssessment, error) {
	rows, err := q.db.Query(ctx, listImpactHistory, featureID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ComplianceImpactAssessment
	for rows.Next() {
		var i ComplianceImpactAssessment
		if err := rows.Scan(
			&i.Seq,
			&i.ID,
			&i.FeatureID,
			&i.ProductID,
			&i.Class,
			&i.Justification,
			&i.Author,
			&i.At,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRequirementSets = `-- name: ListRequirementSets :many
SELECT id, code, version, product_type, items, status, created_by, created_at, updated_at FROM compliance.requirement_sets WHERE ($1::text = '' OR code = $1::text) ORDER BY code, version, id
`

func (q *Queries) ListRequirementSets(ctx context.Context, code string) ([]ComplianceRequirementSet, error) {
	rows, err := q.db.Query(ctx, listRequirementSets, code)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ComplianceRequirementSet
	for rows.Next() {
		var i ComplianceRequirementSet
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Version,
			&i.ProductType,
			&i.Items,
			&i.Status,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTemplates = `-- name: ListTemplates :many
SELECT id, product_type, name, gates, created_at, updated_at FROM compliance.track_templates WHERE ($1::text = '' OR product_type = $1::text) ORDER BY created_at, id
`

func (q *Queries) ListTemplates(ctx context.Context, productType string) ([]ComplianceTrackTemplate, error) {
	rows, err := q.db.Query(ctx, listTemplates, productType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ComplianceTrackTemplate
	for rows.Next() {
		var i ComplianceTrackTemplate
		if err := rows.Scan(
			&i.ID,
			&i.ProductType,
			&i.Name,
			&i.Gates,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTracks = `-- name: ListTracks :many
SELECT id, product_id, release_id, version, template_id, status, gates, baseline_id, created_by, created_at, updated_at FROM compliance.tracks
WHERE ($1::uuid IS NULL OR product_id = $1::uuid)
  AND ($2::uuid IS NULL OR release_id = $2::uuid)
ORDER BY created_at, id
`

type ListTracksParams struct {
	ProductID uuid.NullUUID
	ReleaseID uuid.NullUUID
}

func (q *Queries) ListTracks(ctx context.Context, arg ListTracksParams) ([]ComplianceTrack, error) {
	rows, err := q.db.Query(ctx, listTracks, arg.ProductID, arg.ReleaseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ComplianceTrack
	for rows.Next() {
		var i ComplianceTrack
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.ReleaseID,
			&i.Version,
			&i.TemplateID,
			&i.Status,
			&i.Gates,
			&i.BaselineID,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveSettings = `-- name: SaveSettings :exec
INSERT INTO compliance.settings (singleton, value) VALUES (true, $1)
ON CONFLICT (singleton) DO UPDATE SET value = EXCLUDED.value
`

func (q *Queries) SaveSettings(ctx context.Context, value []byte) error {
	_, err := q.db.Exec(ctx, saveSettings, value)
	return err
}

const upsertBaseline = `-- name: UpsertBaseline :exec
INSERT INTO compliance.baselines (id, product_id, track_id, version, requirement_set_id, certificate_no, certified_at, eol, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT (id) DO UPDATE SET product_id = EXCLUDED.product_id, track_id = EXCLUDED.track_id, version = EXCLUDED.version,
  requirement_set_id = EXCLUDED.requirement_set_id, certificate_no = EXCLUDED.certificate_no, certified_at = EXCLUDED.certified_at, eol = EXCLUDED.eol
`

type UpsertBaselineParams struct {
	ID               uuid.UUID
	ProductID        uuid.UUID
	TrackID          uuid.NullUUID
	Version          string
	RequirementSetID uuid.NullUUID
	CertificateNo    string
	CertifiedAt      pgtype.Date
	Eol              pgtype.Date
	CreatedAt        time.Time
}

func (q *Queries) UpsertBaseline(ctx context.Context, arg UpsertBaselineParams) error {
	_, err := q.db.Exec(ctx, upsertBaseline,
		arg.ID,
		arg.ProductID,
		arg.TrackID,
		arg.Version,
		arg.RequirementSetID,
		arg.CertificateNo,
		arg.CertifiedAt,
		arg.Eol,
		arg.CreatedAt,
	)
	return err
}

const upsertRequirementSet = `-- name: UpsertRequirementSet :exec
INSERT INTO compliance.requirement_sets (id, code, version, product_type, items, status, created_by, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT (id) DO UPDATE SET code = EXCLUDED.code, version = EXCLUDED.version, product_type = EXCLUDED.product_type,
  items = EXCLUDED.items, status = EXCLUDED.status, created_by = EXCLUDED.created_by, updated_at = EXCLUDED.updated_at
`

type UpsertRequirementSetParams struct {
	ID          uuid.UUID
	Code        string
	Version     int64
	ProductType string
	Items       []byte
	Status      string
	CreatedBy   string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

func (q *Queries) UpsertRequirementSet(ctx context.Context, arg UpsertRequirementSetParams) error {
	_, err := q.db.Exec(ctx, upsertRequirementSet,
		arg.ID,
		arg.Code,
		arg.Version,
		arg.ProductType,
		arg.Items,
		arg.Status,
		arg.CreatedBy,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const upsertTemplate = `-- name: UpsertTemplate :exec
INSERT INTO compliance.track_templates (id, product_type, name, gates, created_at, updated_at) VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (id) DO UPDATE SET product_type = EXCLUDED.product_type, name = EXCLUDED.name, gates = EXCLUDED.gates, updated_at = EXCLUDED.updated_at
`

type UpsertTemplateParams struct {
	ID          uuid.UUID
	ProductType string
	Name        string
	Gates       []byte
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

func (q *Queries) UpsertTemplate(ctx context.Context, arg UpsertTemplateParams) error {
	_, err := q.db.Exec(ctx, upsertTemplate,
		arg.ID,
		arg.ProductType,
		arg.Name,
		arg.Gates,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const upsertTrack = `-- name: UpsertTrack :exec
INSERT INTO compliance.tracks (id, product_id, release_id, version, template_id, status, gates, baseline_id, created_by, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
ON CONFLICT (id) DO UPDATE SET product_id = EXCLUDED.product_id, release_id = EXCLUDED.release_id, version = EXCLUDED.version,
  template_id = EXCLUDED.template_id, status = EXCLUDED.status, gates = EXCLUDED.gates, baseline_id = EXCLUDED.baseline_id,
  created_by = EXCLUDED.created_by, updated_at = EXCLUDED.updated_at
`

type UpsertTrackParams struct {
	ID         uuid.UUID
	ProductID  uuid.UUID
	ReleaseID  uuid.UUID
	Version    string
	TemplateID uuid.UUID
	Status     string
	Gates      []byte
	BaselineID uuid.NullUUID
	CreatedBy  string
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

func (q *Queries) UpsertTrack(ctx context.Context, arg UpsertTrackParams) error {
	_, err := q.db.Exec(ctx, upsertTrack,
		arg.ID,
		arg.ProductID,
		arg.ReleaseID,
		arg.Version,
		arg.TemplateID,
		arg.Status,
		arg.Gates,
		arg.BaselineID,
		arg.CreatedBy,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
