// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type ComplianceBaseline struct {
	ID               uuid.UUID
	ProductID        uuid.UUID
	TrackID          uuid.NullUUID
	Version          string
	RequirementSetID uuid.NullUUID
	CertificateNo    string
	CertifiedAt      pgtype.Date
	Eol              pgtype.Date
	CreatedAt        time.Time
	Components       []byte
}

type ComplianceEvidenceLog struct {
	Seq        int64
	ID         uuid.UUID
	ProductID  uuid.UUID
	TrackID    uuid.UUID
	GateID     uuid.UUID
	Url        string
	Sha256     string
	Status     string
	Comment    string
	Supersedes int64
	Actor      string
	At         time.Time
	PrevHash   string
	Hash       string
}

type ComplianceImpactAssessment struct {
	Seq           int64
	ID            uuid.UUID
	FeatureID     uuid.UUID
	ProductID     uuid.UUID
	Class         string
	Justification string
	Author        string
	At            time.Time
}

type ComplianceRequirementSet struct {
	ID          uuid.UUID
	Code        string
	Version     int64
	ProductType string
	Items       []byte
	Status      string
	CreatedBy   string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type ComplianceTrack struct {
	ID         uuid.UUID
	ProductID  uuid.UUID
	ReleaseID  uuid.UUID
	Version    string
	TemplateID uuid.UUID
	Status     string
	Gates      []byte
	BaselineID uuid.NullUUID
	CreatedBy  string
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type ComplianceTrackTemplate struct {
	ID          uuid.UUID
	ProductType string
	Name        string
	Gates       []byte
	CreatedAt   time.Time
	UpdatedAt   time.Time
}
