// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: commitments.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const acknowledgeAlert = `-- name: AcknowledgeAlert :execrows
UPDATE commitments.alerts SET acknowledged = $2, acknowledged_by = $3, acknowledged_at = $4 WHERE id = $1
`

type AcknowledgeAlertParams struct {
	ID             uuid.UUID
	Acknowledged   bool
	AcknowledgedBy string
	AcknowledgedAt pgtype.Timestamptz
}

func (q *Queries) AcknowledgeAlert(ctx context.Context, arg AcknowledgeAlertParams) (int64, error) {
	result, err := q.db.Exec(ctx, acknowledgeAlert,
		arg.ID,
		arg.Acknowledged,
		arg.AcknowledgedBy,
		arg.AcknowledgedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const eventProcessed = `-- name: EventProcessed :one
SELECT EXISTS (SELECT 1 FROM commitments.processed_events WHERE event_id = $1)
`

func (q *Queries) EventProcessed(ctx context.Context, eventID uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, eventProcessed, eventID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getAlert = `-- name: GetAlert :one
SELECT seq, id, commitment_id, product_id, kind, message, event_id, new_date, due_date, raised_at, acknowledged, acknowledged_by, acknowledged_at FROM commitments.alerts WHERE id = $1
`

func (q *Queries) GetAlert(ctx context.Context, id uuid.UUID) (CommitmentsAlert, error) {
	row := q.db.QueryRow(ctx, getAlert, id)
	var i CommitmentsAlert
	err := row.Scan(
		&i.Seq,
		&i.ID,
		&i.CommitmentID,
		&i.ProductID,
		&i.Kind,
		&i.Message,
		&i.EventID,
		&i.NewDate,
		&i.DueDate,
		&i.RaisedAt,
		&i.Acknowledged,
		&i.AcknowledgedBy,
		&i.AcknowledgedAt,
	)
	return i, err
}

const getAlertByEvent = `-- name: GetAlertByEvent :one
SELECT seq, id, commitment_id, product_id, kind, message, event_id, new_date, due_date, raised_at, acknowledged, acknowledged_by, acknowledged_at FROM commitments.alerts WHERE commitment_id = $1 AND event_id = $2 ORDER BY seq LIMIT 1
`

type GetAlertByEventParams struct {
	CommitmentID uuid.UUID
	EventID      uuid.NullUUID
}

func (q *Queries) GetAlertByEvent(ctx context.Context, arg GetAlertByEventParams) (CommitmentsAlert, error) {
	row := q.db.QueryRow(ctx, getAlertByEvent, arg.CommitmentID, arg.EventID)
	var i CommitmentsAlert
	err := row.Scan(
		&i.Seq,
		&i.ID,
		&i.CommitmentID,
		&i.ProductID,
		&i.Kind,
		&i.Message,
		&i.EventID,
		&i.NewDate,
		&i.DueDate,
		&i.RaisedAt,
		&i.Acknowledged,
		&i.AcknowledgedBy,
		&i.AcknowledgedAt,
	)
	return i, err
}

const getCommitment = `-- name: GetCommitment :one
SELECT id, product_id, kind, subtype, counterparty, subject, due_date, basis, owner, status, feature_id, release_id, renewal_item_id, created_by, created_at, updated_at FROM commitments.commitments WHERE id = $1
`

func (q *Queries) GetCommitment(ctx context.Context, id uuid.UUID) (CommitmentsCommitment, error) {
	row := q.db.QueryRow(ctx, getCommitment, id)
	var i CommitmentsCommitment
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Kind,
		&i.Subtype,
		&i.Counterparty,
		&i.Subject,
		&i.DueDate,
		&i.Basis,
		&i.Owner,
		&i.Status,
		&i.FeatureID,
		&i.ReleaseID,
		&i.RenewalItemID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSettings = `-- name: GetSettings :one
SELECT lead_months FROM commitments.settings WHERE id = 1
`

func (q *Queries) GetSettings(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, getSettings)
	var lead_months int64
	err := row.Scan(&lead_months)
	return lead_months, err
}

const insertAlert = `-- name: InsertAlert :exec
INSERT INTO commitments.alerts (id, commitment_id, product_id, kind, message, event_id, new_date, due_date, raised_at, acknowledged, acknowledged_by, acknowledged_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
`

type InsertAlertParams struct {
	ID             uuid.UUID
	CommitmentID   uuid.UUID
	ProductID      uuid.UUID
	Kind           string
	Message        string
	EventID        uuid.NullUUID
	NewDate        pgtype.Date
	DueDate        pgtype.Date
	RaisedAt       time.Time
	Acknowledged   bool
	AcknowledgedBy string
	AcknowledgedAt pgtype.Timestamptz
}

func (q *Queries) InsertAlert(ctx context.Context, arg InsertAlertParams) error {
	_, err := q.db.Exec(ctx, insertAlert,
		arg.ID,
		arg.CommitmentID,
		arg.ProductID,
		arg.Kind,
		arg.Message,
		arg.EventID,
		arg.NewDate,
		arg.DueDate,
		arg.RaisedAt,
		arg.Acknowledged,
		arg.AcknowledgedBy,
		arg.AcknowledgedAt,
	)
	return err
}

const listAlerts = `-- name: ListAlerts :many
SELECT seq, id, commitment_id, product_id, kind, message, event_id, new_date, due_date, raised_at, acknowledged, acknowledged_by, acknowledged_at FROM commitments.alerts WHERE product_id = $1 AND (NOT $2::bool OR NOT acknowledged) ORDER BY seq
`

type ListAlertsParams struct {
	ProductID uuid.UUID
	OnlyOpen  bool
}

func (q *Queries) ListAlerts(ctx context.Context, arg ListAlertsParams) ([]CommitmentsAlert, error) {
	rows, err := q.db.Query(ctx, listAlerts, arg.ProductID, arg.OnlyOpen)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CommitmentsAlert
	for rows.Next() {
		var i CommitmentsAlert
		if err := rows.Scan(
			&i.Seq,
			&i.ID,
			&i.CommitmentID,
			&i.ProductID,
			&i.Kind,
			&i.Message,
			&i.EventID,
			&i.NewDate,
			&i.DueDate,
			&i.RaisedAt,
			&i.Acknowledged,
			&i.AcknowledgedBy,
			&i.AcknowledgedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCommitments = `-- name: ListCommitments :many
SELECT id, product_id, kind, subtype, counterparty, subject, due_date, basis, owner, status, feature_id, release_id, renewal_item_id, created_by, created_at, updated_at FROM commitments.commitments
WHERE ($1::uuid IS NULL OR product_id = $1::uuid)
  AND ($2::text = '' OR kind = $2::text)
  AND ($3::text = '' OR subtype = $3::text)
  AND ($4::uuid IS NULL OR feature_id = $4::uuid)
  AND ($5::uuid IS NULL OR release_id = $5::uuid)
  AND ($6::date IS NULL OR due_date <= $6::date)
  AND (cardinality($7::text[]) = 0 OR status = ANY($7::text[]))
ORDER BY created_at, id
`

type ListCommitmentsParams struct {
	ProductID uuid.NullUUID
	Kind      string
	Subtype   string
	FeatureID uuid.NullUUID
	ReleaseID uuid.NullUUID
	DueBefore pgtype.Date
	Statuses  []string
}

func (q *Queries) ListCommitments(ctx context.Context, arg ListCommitmentsParams) ([]CommitmentsCommitment, error) {
	rows, err := q.db.Query(ctx, listCommitments,
		arg.ProductID,
		arg.Kind,
		arg.Subtype,
		arg.FeatureID,
		arg.ReleaseID,
		arg.DueBefore,
		arg.Statuses,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CommitmentsCommitment
	for rows.Next() {
		var i CommitmentsCommitment
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.Kind,
			&i.Subtype,
			&i.Counterparty,
			&i.Subject,
			&i.DueDate,
			&i.Basis,
			&i.Owner,
			&i.Status,
			&i.FeatureID,
			&i.ReleaseID,
			&i.RenewalItemID,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markEventProcessed = `-- name: MarkEventProcessed :exec
INSERT INTO commitments.processed_events (event_id) VALUES ($1) ON CONFLICT (event_id) DO NOTHING
`

func (q *Queries) MarkEventProcessed(ctx context.Context, eventID uuid.UUID) error {
	_, err := q.db.Exec(ctx, markEventProcessed, eventID)
	return err
}

const upsertCommitment = `-- name: UpsertCommitment :exec
INSERT INTO commitments.commitments (id, product_id, kind, subtype, counterparty, subject, due_date, basis, owner, status, feature_id, release_id, renewal_item_id, created_by, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16)
ON CONFLICT (id) DO UPDATE SET product_id = EXCLUDED.product_id, kind = EXCLUDED.kind, subtype = EXCLUDED.subtype,
  counterparty = EXCLUDED.counterparty, subject = EXCLUDED.subject, due_date = EXCLUDED.due_date, basis = EXCLUDED.basis,
  owner = EXCLUDED.owner, status = EXCLUDED.status, feature_id = EXCLUDED.feature_id, release_id = EXCLUDED.release_id,
  renewal_item_id = EXCLUDED.renewal_item_id, created_by = EXCLUDED.created_by, updated_at = EXCLUDED.updated_at
`

type UpsertCommitmentParams struct {
	ID            uuid.UUID
	ProductID     uuid.UUID
	Kind          string
	Subtype       string
	Counterparty  string
	Subject       string
	DueDate       pgtype.Date
	Basis         string
	Owner         string
	Status        string
	FeatureID     uuid.NullUUID
	ReleaseID     uuid.NullUUID
	RenewalItemID uuid.NullUUID
	CreatedBy     string
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

func (q *Queries) UpsertCommitment(ctx context.Context, arg UpsertCommitmentParams) error {
	_, err := q.db.Exec(ctx, upsertCommitment,
		arg.ID,
		arg.ProductID,
		arg.Kind,
		arg.Subtype,
		arg.Counterparty,
		arg.Subject,
		arg.DueDate,
		arg.Basis,
		arg.Owner,
		arg.Status,
		arg.FeatureID,
		arg.ReleaseID,
		arg.RenewalItemID,
		arg.CreatedBy,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const upsertSettings = `-- name: UpsertSettings :exec
INSERT INTO commitments.settings (id, lead_months, updated_at) VALUES (1, $1, $2)
ON CONFLICT (id) DO UPDATE SET lead_months = EXCLUDED.lead_months, updated_at = EXCLUDED.updated_at
`

type UpsertSettingsParams struct {
	LeadMonths int64
	UpdatedAt  time.Time
}

func (q *Queries) UpsertSettings(ctx context.Context, arg UpsertSettingsParams) error {
	_, err := q.db.Exec(ctx, upsertSettings, arg.LeadMonths, arg.UpdatedAt)
	return err
}
