// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type CommitmentsAlert struct {
	Seq            pgtype.Int8
	ID             uuid.UUID
	CommitmentID   uuid.UUID
	ProductID      uuid.UUID
	Kind           string
	Message        string
	EventID        uuid.NullUUID
	NewDate        pgtype.Date
	DueDate        pgtype.Date
	RaisedAt       time.Time
	Acknowledged   bool
	AcknowledgedBy string
	AcknowledgedAt pgtype.Timestamptz
}

type CommitmentsCommitment struct {
	ID            uuid.UUID
	ProductID     uuid.UUID
	Kind          string
	Subtype       string
	Counterparty  string
	Subject       string
	DueDate       pgtype.Date
	Basis         string
	Owner         string
	Status        string
	FeatureID     uuid.NullUUID
	ReleaseID     uuid.NullUUID
	RenewalItemID uuid.NullUUID
	CreatedBy     string
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type CommitmentsProcessedEvent struct {
	EventID     uuid.UUID
	ProcessedAt time.Time
}

type CommitmentsSetting struct {
	ID         int16
	LeadMonths int64
	UpdatedAt  time.Time
}
