// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: delivery.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const deleteSprintsByProduct = `-- name: DeleteSprintsByProduct :exec
DELETE FROM delivery.sprints WHERE product_id = $1
`

func (q *Queries) DeleteSprintsByProduct(ctx context.Context, productID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteSprintsByProduct, productID)
	return err
}

const getEpicByFeature = `-- name: GetEpicByFeature :one
SELECT feature_id, product_id, epic_key, summary, status, due_date, fix_versions, issues, initial_scope, first_seen_at, synced_at, source_event_id FROM delivery.epics WHERE feature_id = $1
`

func (q *Queries) GetEpicByFeature(ctx context.Context, featureID uuid.UUID) (DeliveryEpic, error) {
	row := q.db.QueryRow(ctx, getEpicByFeature, featureID)
	var i DeliveryEpic
	err := row.Scan(
		&i.FeatureID,
		&i.ProductID,
		&i.EpicKey,
		&i.Summary,
		&i.Status,
		&i.DueDate,
		&i.FixVersions,
		&i.Issues,
		&i.InitialScope,
		&i.FirstSeenAt,
		&i.SyncedAt,
		&i.SourceEventID,
	)
	return i, err
}

const getFieldMapping = `-- name: GetFieldMapping :one
SELECT mapping FROM delivery.field_mapping WHERE id = 1
`

func (q *Queries) GetFieldMapping(ctx context.Context) ([]byte, error) {
	row := q.db.QueryRow(ctx, getFieldMapping)
	var mapping []byte
	err := row.Scan(&mapping)
	return mapping, err
}

const getMappingByEpic = `-- name: GetMappingByEpic :one
SELECT feature_id, product_id, epic_key, project, created_at FROM delivery.mappings WHERE epic_key = $1 ORDER BY created_at, feature_id LIMIT 1
`

func (q *Queries) GetMappingByEpic(ctx context.Context, epicKey string) (DeliveryMapping, error) {
	row := q.db.QueryRow(ctx, getMappingByEpic, epicKey)
	var i DeliveryMapping
	err := row.Scan(
		&i.FeatureID,
		&i.ProductID,
		&i.EpicKey,
		&i.Project,
		&i.CreatedAt,
	)
	return i, err
}

const getMappingByFeature = `-- name: GetMappingByFeature :one
SELECT feature_id, product_id, epic_key, project, created_at FROM delivery.mappings WHERE feature_id = $1
`

func (q *Queries) GetMappingByFeature(ctx context.Context, featureID uuid.UUID) (DeliveryMapping, error) {
	row := q.db.QueryRow(ctx, getMappingByFeature, featureID)
	var i DeliveryMapping
	err := row.Scan(
		&i.FeatureID,
		&i.ProductID,
		&i.EpicKey,
		&i.Project,
		&i.CreatedAt,
	)
	return i, err
}

const getSyncState = `-- name: GetSyncState :one
SELECT id, last_success_at, last_attempt_at, last_error, lag_ns, stale FROM delivery.sync_state WHERE id = 1
`

func (q *Queries) GetSyncState(ctx context.Context) (DeliverySyncState, error) {
	row := q.db.QueryRow(ctx, getSyncState)
	var i DeliverySyncState
	err := row.Scan(
		&i.ID,
		&i.LastSuccessAt,
		&i.LastAttemptAt,
		&i.LastError,
		&i.LagNs,
		&i.Stale,
	)
	return i, err
}

const insertSprint = `-- name: InsertSprint :exec
INSERT INTO delivery.sprints (product_id, position, board, sprint_id, name, goal, state, start_date, end_date, issues, total, done, carried_over, synced_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
`

type InsertSprintParams struct {
	ProductID   uuid.UUID
	Position    int64
	Board       string
	SprintID    string
	Name        string
	Goal        string
	State       string
	StartDate   pgtype.Date
	EndDate     pgtype.Date
	Issues      []byte
	Total       int64
	Done        int64
	CarriedOver []string
	SyncedAt    pgtype.Timestamptz
}

func (q *Queries) InsertSprint(ctx context.Context, arg InsertSprintParams) error {
	_, err := q.db.Exec(ctx, insertSprint,
		arg.ProductID,
		arg.Position,
		arg.Board,
		arg.SprintID,
		arg.Name,
		arg.Goal,
		arg.State,
		arg.StartDate,
		arg.EndDate,
		arg.Issues,
		arg.Total,
		arg.Done,
		arg.CarriedOver,
		arg.SyncedAt,
	)
	return err
}

const listMappings = `-- name: ListMappings :many
SELECT feature_id, product_id, epic_key, project, created_at FROM delivery.mappings ORDER BY epic_key, feature_id
`

func (q *Queries) ListMappings(ctx context.Context) ([]DeliveryMapping, error) {
	rows, err := q.db.Query(ctx, listMappings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DeliveryMapping
	for rows.Next() {
		var i DeliveryMapping
		if err := rows.Scan(
			&i.FeatureID,
			&i.ProductID,
			&i.EpicKey,
			&i.Project,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReleaseMappings = `-- name: ListReleaseMappings :many
SELECT release_id, product_id, project, fix_version, created_at FROM delivery.release_mappings ORDER BY fix_version, release_id
`

func (q *Queries) ListReleaseMappings(ctx context.Context) ([]DeliveryReleaseMapping, error) {
	rows, err := q.db.Query(ctx, listReleaseMappings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DeliveryReleaseMapping
	for rows.Next() {
		var i DeliveryReleaseMapping
		if err := rows.Scan(
			&i.ReleaseID,
			&i.ProductID,
			&i.Project,
			&i.FixVersion,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSprintsByProduct = `-- name: ListSprintsByProduct :many
SELECT product_id, position, board, sprint_id, name, goal, state, start_date, end_date, issues, total, done, carried_over, synced_at FROM delivery.sprints WHERE product_id = $1 ORDER BY position
`

func (q *Queries) ListSprintsByProduct(ctx context.Context, productID uuid.UUID) ([]DeliverySprint, error) {
	rows, err := q.db.Query(ctx, listSprintsByProduct, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DeliverySprint
	for rows.Next() {
		var i DeliverySprint
		if err := rows.Scan(
			&i.ProductID,
			&i.Position,
			&i.Board,
			&i.SprintID,
			&i.Name,
			&i.Goal,
			&i.State,
			&i.StartDate,
			&i.EndDate,
			&i.Issues,
			&i.Total,
			&i.Done,
			&i.CarriedOver,
			&i.SyncedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markProcessed = `-- name: MarkProcessed :execrows
INSERT INTO delivery.processed_events (external_id) VALUES ($1) ON CONFLICT (external_id) DO NOTHING
`

func (q *Queries) MarkProcessed(ctx context.Context, externalID string) (int64, error) {
	result, err := q.db.Exec(ctx, markProcessed, externalID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertEpic = `-- name: UpsertEpic :exec
INSERT INTO delivery.epics (feature_id, product_id, epic_key, summary, status, due_date, fix_versions, issues, initial_scope, first_seen_at, synced_at, source_event_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
ON CONFLICT (feature_id) DO UPDATE SET product_id = EXCLUDED.product_id, epic_key = EXCLUDED.epic_key, summary = EXCLUDED.summary,
  status = EXCLUDED.status, due_date = EXCLUDED.due_date, fix_versions = EXCLUDED.fix_versions, issues = EXCLUDED.issues,
  initial_scope = EXCLUDED.initial_scope, first_seen_at = EXCLUDED.first_seen_at, synced_at = EXCLUDED.synced_at,
  source_event_id = EXCLUDED.source_event_id
`

type UpsertEpicParams struct {
	FeatureID     uuid.UUID
	ProductID     uuid.UUID
	EpicKey       string
	Summary       string
	Status        string
	DueDate       pgtype.Date
	FixVersions   []string
	Issues        []byte
	InitialScope  []string
	FirstSeenAt   pgtype.Timestamptz
	SyncedAt      pgtype.Timestamptz
	SourceEventID string
}

func (q *Queries) UpsertEpic(ctx context.Context, arg UpsertEpicParams) error {
	_, err := q.db.Exec(ctx, upsertEpic,
		arg.FeatureID,
		arg.ProductID,
		arg.EpicKey,
		arg.Summary,
		arg.Status,
		arg.DueDate,
		arg.FixVersions,
		arg.Issues,
		arg.InitialScope,
		arg.FirstSeenAt,
		arg.SyncedAt,
		arg.SourceEventID,
	)
	return err
}

const upsertFieldMapping = `-- name: UpsertFieldMapping :exec
INSERT INTO delivery.field_mapping (id, mapping, updated_at) VALUES (1, $1, $2)
ON CONFLICT (id) DO UPDATE SET mapping = EXCLUDED.mapping, updated_at = EXCLUDED.updated_at
`

type UpsertFieldMappingParams struct {
	Mapping   []byte
	UpdatedAt time.Time
}

func (q *Queries) UpsertFieldMapping(ctx context.Context, arg UpsertFieldMappingParams) error {
	_, err := q.db.Exec(ctx, upsertFieldMapping, arg.Mapping, arg.UpdatedAt)
	return err
}

const upsertMapping = `-- name: UpsertMapping :exec
INSERT INTO delivery.mappings (feature_id, product_id, epic_key, project, created_at) VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (feature_id) DO UPDATE SET product_id = EXCLUDED.product_id, epic_key = EXCLUDED.epic_key,
  project = EXCLUDED.project, created_at = EXCLUDED.created_at
`

type UpsertMappingParams struct {
	FeatureID uuid.UUID
	ProductID uuid.UUID
	EpicKey   string
	Project   string
	CreatedAt time.Time
}

func (q *Queries) UpsertMapping(ctx context.Context, arg UpsertMappingParams) error {
	_, err := q.db.Exec(ctx, upsertMapping,
		arg.FeatureID,
		arg.ProductID,
		arg.EpicKey,
		arg.Project,
		arg.CreatedAt,
	)
	return err
}

const upsertReleaseMapping = `-- name: UpsertReleaseMapping :exec
INSERT INTO delivery.release_mappings (release_id, product_id, project, fix_version, created_at) VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (release_id) DO UPDATE SET product_id = EXCLUDED.product_id, project = EXCLUDED.project,
  fix_version = EXCLUDED.fix_version, created_at = EXCLUDED.created_at
`

type UpsertReleaseMappingParams struct {
	ReleaseID  uuid.UUID
	ProductID  uuid.UUID
	Project    string
	FixVersion string
	CreatedAt  time.Time
}

func (q *Queries) UpsertReleaseMapping(ctx context.Context, arg UpsertReleaseMappingParams) error {
	_, err := q.db.Exec(ctx, upsertReleaseMapping,
		arg.ReleaseID,
		arg.ProductID,
		arg.Project,
		arg.FixVersion,
		arg.CreatedAt,
	)
	return err
}

const upsertSyncState = `-- name: UpsertSyncState :exec
INSERT INTO delivery.sync_state (id, last_success_at, last_attempt_at, last_error, lag_ns, stale) VALUES (1, $1, $2, $3, $4, $5)
ON CONFLICT (id) DO UPDATE SET last_success_at = EXCLUDED.last_success_at, last_attempt_at = EXCLUDED.last_attempt_at,
  last_error = EXCLUDED.last_error, lag_ns = EXCLUDED.lag_ns, stale = EXCLUDED.stale
`

type UpsertSyncStateParams struct {
	LastSuccessAt pgtype.Timestamptz
	LastAttemptAt pgtype.Timestamptz
	LastError     string
	LagNs         int64
	Stale         bool
}

func (q *Queries) UpsertSyncState(ctx context.Context, arg UpsertSyncStateParams) error {
	_, err := q.db.Exec(ctx, upsertSyncState,
		arg.LastSuccessAt,
		arg.LastAttemptAt,
		arg.LastError,
		arg.LagNs,
		arg.Stale,
	)
	return err
}
