// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type DeliveryEpic struct {
	FeatureID     uuid.UUID
	ProductID     uuid.UUID
	EpicKey       string
	Summary       string
	Status        string
	DueDate       pgtype.Date
	FixVersions   []string
	Issues        []byte
	InitialScope  []string
	FirstSeenAt   pgtype.Timestamptz
	SyncedAt      pgtype.Timestamptz
	SourceEventID string
}

type DeliveryFieldMapping struct {
	ID        int16
	Mapping   []byte
	UpdatedAt time.Time
}

type DeliveryMapping struct {
	FeatureID uuid.UUID
	ProductID uuid.UUID
	EpicKey   string
	Project   string
	CreatedAt time.Time
}

type DeliveryProcessedEvent struct {
	ExternalID  string
	ProcessedAt time.Time
}

type DeliveryReleaseMapping struct {
	ReleaseID  uuid.UUID
	ProductID  uuid.UUID
	Project    string
	FixVersion string
	CreatedAt  time.Time
}

type DeliverySprint struct {
	ProductID   uuid.UUID
	Position    int64
	Board       string
	SprintID    string
	Name        string
	Goal        string
	State       string
	StartDate   pgtype.Date
	EndDate     pgtype.Date
	Issues      []byte
	Total       int64
	Done        int64
	CarriedOver []string
	SyncedAt    pgtype.Timestamptz
}

type DeliverySyncState struct {
	ID            int16
	LastSuccessAt pgtype.Timestamptz
	LastAttemptAt pgtype.Timestamptz
	LastError     string
	LagNs         int64
	Stale         bool
}
