// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: economics.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const appendSnapshot = `-- name: AppendSnapshot :execrows
INSERT INTO economics.snapshots (id, product_id, period, version, body, created_at)
SELECT $1, $2, $3, $4, $5, $6
WHERE (SELECT COALESCE(MAX(version),0) FROM economics.snapshots WHERE product_id=$2 AND period=$3) = $7::integer
`

type AppendSnapshotParams struct {
	ID              uuid.UUID
	ProductID       uuid.UUID
	Period          string
	Version         int32
	Body            []byte
	CreatedAt       time.Time
	ExpectedVersion int32
}

func (q *Queries) AppendSnapshot(ctx context.Context, arg AppendSnapshotParams) (int64, error) {
	result, err := q.db.Exec(ctx, appendSnapshot,
		arg.ID,
		arg.ProductID,
		arg.Period,
		arg.Version,
		arg.Body,
		arg.CreatedAt,
		arg.ExpectedVersion,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getSnapshot = `-- name: GetSnapshot :one
SELECT body FROM economics.snapshots
WHERE product_id = $1 AND period = $2 AND ($3::integer = 0 OR version = $3::integer)
ORDER BY version DESC LIMIT 1
`

type GetSnapshotParams struct {
	ProductID        uuid.UUID
	Period           string
	RequestedVersion int32
}

func (q *Queries) GetSnapshot(ctx context.Context, arg GetSnapshotParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, getSnapshot, arg.ProductID, arg.Period, arg.RequestedVersion)
	var body []byte
	err := row.Scan(&body)
	return body, err
}

const listImportTemplates = `-- name: ListImportTemplates :many
SELECT body FROM economics.import_templates WHERE product_id=$1 ORDER BY name
`

func (q *Queries) ListImportTemplates(ctx context.Context, productID uuid.UUID) ([][]byte, error) {
	rows, err := q.db.Query(ctx, listImportTemplates, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items [][]byte
	for rows.Next() {
		var body []byte
		if err := rows.Scan(&body); err != nil {
			return nil, err
		}
		items = append(items, body)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSnapshots = `-- name: ListSnapshots :many
SELECT body FROM economics.snapshots WHERE product_id = $1 AND period = $2 ORDER BY version
`

type ListSnapshotsParams struct {
	ProductID uuid.UUID
	Period    string
}

func (q *Queries) ListSnapshots(ctx context.Context, arg ListSnapshotsParams) ([][]byte, error) {
	rows, err := q.db.Query(ctx, listSnapshots, arg.ProductID, arg.Period)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items [][]byte
	for rows.Next() {
		var body []byte
		if err := rows.Scan(&body); err != nil {
			return nil, err
		}
		items = append(items, body)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertImportTemplate = `-- name: UpsertImportTemplate :exec
INSERT INTO economics.import_templates(product_id,name,body) VALUES ($1,$2,$3)
ON CONFLICT(product_id,name) DO UPDATE SET body=EXCLUDED.body
`

type UpsertImportTemplateParams struct {
	ProductID uuid.UUID
	Name      string
	Body      []byte
}

func (q *Queries) UpsertImportTemplate(ctx context.Context, arg UpsertImportTemplateParams) error {
	_, err := q.db.Exec(ctx, upsertImportTemplate, arg.ProductID, arg.Name, arg.Body)
	return err
}
