// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"

	"github.com/google/uuid"
)

type EconomicsImportTemplate struct {
	ProductID uuid.UUID
	Name      string
	Body      []byte
}

type EconomicsSnapshot struct {
	ID        uuid.UUID
	ProductID uuid.UUID
	Period    string
	Version   int32
	Body      []byte
	CreatedAt time.Time
}
