// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"

	"github.com/google/uuid"
)

type AuditRecord struct {
	Seq        int64
	At         time.Time
	Actor      string
	Action     string
	ObjectType string
	ObjectID   string
	ProductID  uuid.NullUUID
	Details    []byte
	PrevHash   string
	Hash       string
}
