// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: records.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const insertRecord = `-- name: InsertRecord :exec
INSERT INTO audit.records (seq, at, actor, action, object_type, object_id, product_id, details, prev_hash, hash)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
`

type InsertRecordParams struct {
	Seq        int64
	At         time.Time
	Actor      string
	Action     string
	ObjectType string
	ObjectID   string
	ProductID  uuid.NullUUID
	Details    []byte
	PrevHash   string
	Hash       string
}

func (q *Queries) InsertRecord(ctx context.Context, arg InsertRecordParams) error {
	_, err := q.db.Exec(ctx, insertRecord,
		arg.Seq,
		arg.At,
		arg.Actor,
		arg.Action,
		arg.ObjectType,
		arg.ObjectID,
		arg.ProductID,
		arg.Details,
		arg.PrevHash,
		arg.Hash,
	)
	return err
}

const lastRecord = `-- name: LastRecord :one
SELECT seq, at, actor, action, object_type, object_id, product_id, details, prev_hash, hash
FROM audit.records ORDER BY seq DESC LIMIT 1
`

func (q *Queries) LastRecord(ctx context.Context) (AuditRecord, error) {
	row := q.db.QueryRow(ctx, lastRecord)
	var i AuditRecord
	err := row.Scan(
		&i.Seq,
		&i.At,
		&i.Actor,
		&i.Action,
		&i.ObjectType,
		&i.ObjectID,
		&i.ProductID,
		&i.Details,
		&i.PrevHash,
		&i.Hash,
	)
	return i, err
}

const recordsAfter = `-- name: RecordsAfter :many
SELECT seq, at, actor, action, object_type, object_id, product_id, details, prev_hash, hash
FROM audit.records WHERE seq > $1 ORDER BY seq LIMIT $2
`

type RecordsAfterParams struct {
	Seq   int64
	Limit int32
}

func (q *Queries) RecordsAfter(ctx context.Context, arg RecordsAfterParams) ([]AuditRecord, error) {
	rows, err := q.db.Query(ctx, recordsAfter, arg.Seq, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditRecord
	for rows.Next() {
		var i AuditRecord
		if err := rows.Scan(
			&i.Seq,
			&i.At,
			&i.Actor,
			&i.Action,
			&i.ObjectType,
			&i.ObjectID,
			&i.ProductID,
			&i.Details,
			&i.PrevHash,
			&i.Hash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
