// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type SignalsSignal struct {
	ID                 uuid.UUID
	ProductID          uuid.UUID
	Source             string
	Text               string
	ExternalKey        string
	AccountID          string
	DealID             string
	Version            string
	Segment            string
	WeightAmount       int64
	WeightCurrency     string
	AccountArrAmount   int64
	AccountArrCurrency string
	BlocksDeal         bool
	Status             string
	DueDate            pgtype.Date
	FeatureID          uuid.NullUUID
	ContractID         uuid.NullUUID
	HypothesisID       uuid.NullUUID
	MergedInto         uuid.NullUUID
	CreatedBy          string
	CreatedAt          time.Time
	UpdatedAt          time.Time
}
