// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: signals.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getSignal = `-- name: GetSignal :one
SELECT id, product_id, source, text, external_key, account_id, deal_id, version, segment, weight_amount, weight_currency, account_arr_amount, account_arr_currency, blocks_deal, status, due_date, feature_id, contract_id, hypothesis_id, merged_into, created_by, created_at, updated_at FROM signals.signals WHERE id = $1
`

func (q *Queries) GetSignal(ctx context.Context, id uuid.UUID) (SignalsSignal, error) {
	row := q.db.QueryRow(ctx, getSignal, id)
	var i SignalsSignal
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Source,
		&i.Text,
		&i.ExternalKey,
		&i.AccountID,
		&i.DealID,
		&i.Version,
		&i.Segment,
		&i.WeightAmount,
		&i.WeightCurrency,
		&i.AccountArrAmount,
		&i.AccountArrCurrency,
		&i.BlocksDeal,
		&i.Status,
		&i.DueDate,
		&i.FeatureID,
		&i.ContractID,
		&i.HypothesisID,
		&i.MergedInto,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSignalByExternalKey = `-- name: GetSignalByExternalKey :one
SELECT id, product_id, source, text, external_key, account_id, deal_id, version, segment, weight_amount, weight_currency, account_arr_amount, account_arr_currency, blocks_deal, status, due_date, feature_id, contract_id, hypothesis_id, merged_into, created_by, created_at, updated_at FROM signals.signals WHERE external_key = $1 AND external_key <> '' ORDER BY created_at, id LIMIT 1
`

func (q *Queries) GetSignalByExternalKey(ctx context.Context, externalKey string) (SignalsSignal, error) {
	row := q.db.QueryRow(ctx, getSignalByExternalKey, externalKey)
	var i SignalsSignal
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Source,
		&i.Text,
		&i.ExternalKey,
		&i.AccountID,
		&i.DealID,
		&i.Version,
		&i.Segment,
		&i.WeightAmount,
		&i.WeightCurrency,
		&i.AccountArrAmount,
		&i.AccountArrCurrency,
		&i.BlocksDeal,
		&i.Status,
		&i.DueDate,
		&i.FeatureID,
		&i.ContractID,
		&i.HypothesisID,
		&i.MergedInto,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSignals = `-- name: ListSignals :many
SELECT id, product_id, source, text, external_key, account_id, deal_id, version, segment, weight_amount, weight_currency, account_arr_amount, account_arr_currency, blocks_deal, status, due_date, feature_id, contract_id, hypothesis_id, merged_into, created_by, created_at, updated_at FROM signals.signals
WHERE ($1::uuid IS NULL OR product_id = $1::uuid)
  AND ($2::uuid IS NULL OR feature_id = $2::uuid)
  AND ($3::uuid IS NULL OR contract_id = $3::uuid)
  AND ($4::uuid IS NULL OR hypothesis_id = $4::uuid)
  AND (cardinality($5::text[]) = 0 OR status = ANY($5::text[]))
ORDER BY created_at, id
`

type ListSignalsParams struct {
	ProductID    uuid.NullUUID
	FeatureID    uuid.NullUUID
	ContractID   uuid.NullUUID
	HypothesisID uuid.NullUUID
	Statuses     []string
}

func (q *Queries) ListSignals(ctx context.Context, arg ListSignalsParams) ([]SignalsSignal, error) {
	rows, err := q.db.Query(ctx, listSignals,
		arg.ProductID,
		arg.FeatureID,
		arg.ContractID,
		arg.HypothesisID,
		arg.Statuses,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SignalsSignal
	for rows.Next() {
		var i SignalsSignal
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.Source,
			&i.Text,
			&i.ExternalKey,
			&i.AccountID,
			&i.DealID,
			&i.Version,
			&i.Segment,
			&i.WeightAmount,
			&i.WeightCurrency,
			&i.AccountArrAmount,
			&i.AccountArrCurrency,
			&i.BlocksDeal,
			&i.Status,
			&i.DueDate,
			&i.FeatureID,
			&i.ContractID,
			&i.HypothesisID,
			&i.MergedInto,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertSignal = `-- name: UpsertSignal :exec
INSERT INTO signals.signals (id, product_id, source, text, external_key, account_id, deal_id, version, segment,
  weight_amount, weight_currency, account_arr_amount, account_arr_currency, blocks_deal, status, due_date,
  feature_id, contract_id, hypothesis_id, merged_into, created_by, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21, $22, $23)
ON CONFLICT (id) DO UPDATE SET
  product_id = EXCLUDED.product_id, source = EXCLUDED.source, text = EXCLUDED.text, external_key = EXCLUDED.external_key,
  account_id = EXCLUDED.account_id, deal_id = EXCLUDED.deal_id, version = EXCLUDED.version, segment = EXCLUDED.segment,
  weight_amount = EXCLUDED.weight_amount, weight_currency = EXCLUDED.weight_currency,
  account_arr_amount = EXCLUDED.account_arr_amount, account_arr_currency = EXCLUDED.account_arr_currency,
  blocks_deal = EXCLUDED.blocks_deal, status = EXCLUDED.status, due_date = EXCLUDED.due_date,
  feature_id = EXCLUDED.feature_id, contract_id = EXCLUDED.contract_id, hypothesis_id = EXCLUDED.hypothesis_id,
  merged_into = EXCLUDED.merged_into, created_by = EXCLUDED.created_by, updated_at = EXCLUDED.updated_at
`

type UpsertSignalParams struct {
	ID                 uuid.UUID
	ProductID          uuid.UUID
	Source             string
	Text               string
	ExternalKey        string
	AccountID          string
	DealID             string
	Version            string
	Segment            string
	WeightAmount       int64
	WeightCurrency     string
	AccountArrAmount   int64
	AccountArrCurrency string
	BlocksDeal         bool
	Status             string
	DueDate            pgtype.Date
	FeatureID          uuid.NullUUID
	ContractID         uuid.NullUUID
	HypothesisID       uuid.NullUUID
	MergedInto         uuid.NullUUID
	CreatedBy          string
	CreatedAt          time.Time
	UpdatedAt          time.Time
}

func (q *Queries) UpsertSignal(ctx context.Context, arg UpsertSignalParams) error {
	_, err := q.db.Exec(ctx, upsertSignal,
		arg.ID,
		arg.ProductID,
		arg.Source,
		arg.Text,
		arg.ExternalKey,
		arg.AccountID,
		arg.DealID,
		arg.Version,
		arg.Segment,
		arg.WeightAmount,
		arg.WeightCurrency,
		arg.AccountArrAmount,
		arg.AccountArrCurrency,
		arg.BlocksDeal,
		arg.Status,
		arg.DueDate,
		arg.FeatureID,
		arg.ContractID,
		arg.HypothesisID,
		arg.MergedInto,
		arg.CreatedBy,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
