// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: documents.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const appendDocument = `-- name: AppendDocument :exec
INSERT INTO modeling.documents(kind, key, revision, product_id, body)
SELECT $1, $2, COALESCE(MAX(revision), 0) + 1, $3, $4 FROM modeling.documents WHERE kind = $1 AND key = $2
`

type AppendDocumentParams struct {
	Kind      string
	Key       string
	ProductID uuid.UUID
	Body      []byte
}

func (q *Queries) AppendDocument(ctx context.Context, arg AppendDocumentParams) error {
	_, err := q.db.Exec(ctx, appendDocument,
		arg.Kind,
		arg.Key,
		arg.ProductID,
		arg.Body,
	)
	return err
}

const getDocument = `-- name: GetDocument :one
SELECT body FROM modeling.documents WHERE kind = $1 AND key = $2 ORDER BY revision DESC LIMIT 1
`

type GetDocumentParams struct {
	Kind string
	Key  string
}

func (q *Queries) GetDocument(ctx context.Context, arg GetDocumentParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, getDocument, arg.Kind, arg.Key)
	var body []byte
	err := row.Scan(&body)
	return body, err
}

const listDocuments = `-- name: ListDocuments :many
SELECT DISTINCT ON (key) key, body FROM modeling.documents WHERE kind = $1 ORDER BY key, revision DESC
`

type ListDocumentsRow struct {
	Key  string
	Body []byte
}

func (q *Queries) ListDocuments(ctx context.Context, kind string) ([]ListDocumentsRow, error) {
	rows, err := q.db.Query(ctx, listDocuments, kind)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDocumentsRow
	for rows.Next() {
		var i ListDocumentsRow
		if err := rows.Scan(&i.Key, &i.Body); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFacts = `-- name: ListFacts :many
SELECT f.body FROM modeling.documents f
JOIN modeling.documents b ON b.kind = 'batch' AND b.key = f.body->>'batch_id'
WHERE f.kind = 'fact' AND b.body->>'status' = 'applied'
AND ($1::boolean OR f.product_id = ANY($2::uuid[]))
AND CASE WHEN $3::boolean
THEN (f.body->>'data_version')::bigint = $4::bigint
ELSE (f.body->>'data_version')::bigint = (
 SELECT max((latest.body->>'data_version')::bigint) FROM modeling.documents latest
 WHERE latest.kind = 'batch' AND latest.body->>'status' = 'applied'
 AND latest.body->>'period' = f.body->>'period'
) END
ORDER BY f.key
`

type ListFactsParams struct {
	AllProducts     bool
	Products        []uuid.UUID
	ExplicitVersion bool
	DataVersion     int64
}

func (q *Queries) ListFacts(ctx context.Context, arg ListFactsParams) ([][]byte, error) {
	rows, err := q.db.Query(ctx, listFacts,
		arg.AllProducts,
		arg.Products,
		arg.ExplicitVersion,
		arg.DataVersion,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items [][]byte
	for rows.Next() {
		var body []byte
		if err := rows.Scan(&body); err != nil {
			return nil, err
		}
		items = append(items, body)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
