// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"

	"github.com/google/uuid"
)

type ModelingDocument struct {
	Kind      string
	Key       string
	Revision  int64
	ProductID uuid.UUID
	Body      []byte
	CreatedAt time.Time
}
